fix: 1.18.5 から 1.18.1 に修正
jaoafa/jaoweb-docs pull request #125
Opened 2022-02-26 10:55 UTC by yuuahp

https://github.com/jaoafa/jaoweb-docs/pull/123#issuecomment-1051973992

2022-02-26 10:59 UTC, Hiratake requested changes

2022-02-26 10:59 UTC, Hiratake commented on server/specifications.md
> +当サーバのバージョンは<big>**1.18.1**</big>ですが、以下のバージョンでもログインが可能です。
`big` タグって廃止されてると思うのだけど、どうしてもこの部分だけ文字サイズを大きくしないといけない？  
普通に太字だけでいい気がする。  
https://developer.mozilla.org/ja/docs/Web/HTML/Element/big

2022-02-26 12:42 UTC, book000 approved these changes

2022-02-26 12:42 UTC, book000 commented
@Hiratake approveしたらマージもいっしょにしちゃってください

2022-02-27 09:16 UTC, book000 approved these changes

2022-02-27 09:17 UTC, Hiratake approved these changes

2022-02-27 09:17 UTC, merged