軽微な修正
jaoafa/jaoweb-docs pull request #144
Opened 2022-05-10 13:53 UTC by Omuretsu

各ページについて、表現の修正など軽微な編集を行いました。
編集したページ数が多いため、具体的な変更に関しては各変更を参照してください。

2022-05-10 15:01 UTC, book000 commented
> server/guidelines/railways.md: 更新日時が変更されていません (Sat Mar 12 2022 00:00:00 GMT+0000 (Coordinated Universal Time))

2022-05-10 16:04 UTC, book000 requested changes
多いな…。

2022-05-10 16:04 UTC, book000 commented on support/faq.md
> +サーバへの再参加やMinecraftクライアントの再起動を行っても解決しない場合は、[公式Discordサーバ](/blog/join-discord) `#support`チャンネルや[お問い合わせフォーム](https://forms.gle/Rpj1ZV76p2NsdWMK6)を用いて、以下の内容を記述した上で運営まで問い合わせを行ってください。
こちらも、お問い合わせページ(`/contact`)にリンクしてしまっていいかと

2022-05-10 16:04 UTC, book000 commented on support/faq.md
> +## jao Minecraft Serverの運営と連絡を取りたい
```suggestion
## Q. jao Minecraft Serverの運営と連絡を取りたい
```

他と合わせて `Q.` を入れるか、他のQ.を消すか…

2022-05-10 16:05 UTC, book000 commented
割とえきぱ氏が書いてそうなところの変更もあるので、レビュアーにえきぱ氏を入れておきます。

2022-05-10 17:47 UTC, Omuretsu commented
とりあえず、確認できた範囲内でsuggestionをcommitしました。jaox
残りは明日以降に確認します。

2022-05-11 00:10 UTC, book000 commented on server/profiles.md
> +|![Ekusas83](https://storage.jaoafa.com/b7e612706c25b7bb967dc6faa7ab63ce.png)|Ekusas|Ekusas83|[@ekusas55000](https://twitter.com/ekusas55000)|[ekusas#8352](https://discord.com/users/18937705495579852
うーん、なるほど。
やるなら区切り文字をスラッシュとかに変えるとかだけど…微妙だよなあ…。

2022-05-11 07:46 UTC, minhero-exp commented on server/beginners.md
> +自由建築エリアである爆新地の外には「自治体」と呼ばれる個人の領域を取得することができます。 自治体は「自由建築可能区域」とは異なり、その自治体の管理者と、その自治体が許可したプレイヤーのみが自由に編集することができます。
「爆新地」の表記が残っているので、ついでに修正しておいて下さい🙏

2022-05-11 07:46 UTC, minhero-exp commented on server/policies/bans.md
> +- 迷惑行為により他利用者の建築物等に対して損害があった場合、運営はロールバック(復元)等などの、可能な限りの対応を致します。しかしこれは、完全な復元を保証するものではありません。
「等」と「など」が被っています。

2022-05-11 07:46 UTC, minhero-exp commented on server/profiles.md
>  |![MinHero_exp](https://storage.jaoafa.com/fb68e673c41ce79f66bd5b930f8be5d5.png)|EKipa|MinHero_exp|[@minhero_exp](https://twitter.com/minhero_exp)|[minhero_exp#3751](https://discord.com/users/3105707
ごめんなさい、ここにも「爆新地」がいるので修正しておいて下さい

2022-05-11 09:33 UTC, Omuretsu commented on server/profiles.md
>  |![MinHero_exp](https://storage.jaoafa.com/fb68e673c41ce79f66bd5b930f8be5d5.png)|EKipa|MinHero_exp|[@minhero_exp](https://twitter.com/minhero_exp)|[minhero_exp#3751](https://discord.com/users/3105707
https://github.com/jaoafa/jaoweb-docs/pull/144/commits/584781478e752a5ab73de35a62ef37b13e08ac04
以上にて修正しました。

2022-05-11 09:33 UTC, Omuretsu commented on server/beginners.md
> +自由建築エリアである爆新地の外には「自治体」と呼ばれる個人の領域を取得することができます。 自治体は「自由建築可能区域」とは異なり、その自治体の管理者と、その自治体が許可したプレイヤーのみが自由に編集することができます。
https://github.com/jaoafa/jaoweb-docs/pull/144/commits/584781478e752a5ab73de35a62ef37b13e08ac04
以上にて修正しました。

2022-05-11 09:37 UTC, Omuretsu commented on server/guidelines/communications.md
> +当サーバの運営はDiscord内のサーバを運営するに当たり、Discord公式が定める利用規約とガイドラインに同意しています。
チャットによるコミュニケーションの定義などもしているので、どちらかというと「当サーバ」自体を定義しちゃった方がいいかもしれないですね

2022-05-11 09:39 UTC, Omuretsu commented on server/guidelines/broadcasts.md
> +また、他人の建造物を自らが作ったと偽ってスクリーンショットを公開する、といった行為もお控えください。
どちらかというと「基本要件」を定義した上で、「静止画」と「動画」それぞれを記したほうがいいかもですね。

2022-05-11 09:41 UTC, Omuretsu commented on server/guidelines/communications.md
> +他サーバの名前やサーバURLなど、他サーバに関する話題などの発言を運営として禁止することはありません。しかし他利用者からやめるよう言われた場合には、即座にやめていただきますようお願い申し上げます。
https://github.com/jaoafa/jaoweb-docs/pull/144/commits/91610cca7d945c3b795a790c333fd3d8118d9d99 にて修正しました。

2022-05-11 09:47 UTC, Omuretsu commented on support/faq.md
> +  Minecraftアカウントの紛失などでメインアカウントを変更する必要が生じた際は、公式Discordサーバ`#support`へどうぞ。
```suggestion
  Minecraftアカウントにアクセスできないなどの理由により、メインアカウントを変更する必要が生じた際は、公式Discordサーバ`#support`へどうぞ。
```
以上でどうでしょうか？

2022-05-11 09:50 UTC, Omuretsu commented on server/guidelines/railways.md
> +自分で撤去等をせず、[公式Discordサーバ](/blog/join-discord)の`#support`か[お問い合せフォーム](https://forms.gle/Rpj1ZV76p2NsdWMK6)を用いて、運営に「領土侵犯を被った旨」と「領土侵犯を被った座標」を報告してください。
```suggestion
自分で撤去等をせず、各種[お問い合わせ手段](/support/inquiry)を用いて、運営に「領土侵犯を被った旨」と「領土侵犯を被った座標」を報告してください。
```
以上でどうでしょうか。

2022-05-11 09:51 UTC, Omuretsu commented on server/specifications.md
> +しかし安定した動作のため、**毎朝3時（深夜27時）に自動で再起動**しています。
```suggestion
しかし安定した動作のため、**毎朝3時に自動で再起動**しています。  
```
修正（削除）しました。

2022-05-11 09:53 UTC, Omuretsu commented on support/faq.md
> +  Bedrock版のMinecraftで当サーバにログインすることはできません。Java版を購入しましょう。
https://github.com/jaoafa/jaoweb-docs/pull/144/commits/466c7fbc7b763a81b15c1bad2caf01ff03691839 にて修正しました。

2022-05-11 10:03 UTC, book000 commented
:+1: をつけました。そのまま採用しちゃってよさそうです

2022-05-11 10:08 UTC, Omuretsu commented on support/faq.md
> +サーバへの再参加やMinecraftクライアントの再起動を行っても解決しない場合は、[公式Discordサーバ](/blog/join-discord) `#support`チャンネルや[お問い合わせフォーム](https://forms.gle/Rpj1ZV76p2NsdWMK6)を用いて、以下の内容を記述した上で運営まで問い合わせを行ってください。
```suggestion
サーバへの再参加やMinecraftクライアントの再起動を行っても解決しない場合は、各種[お問い合わせ手段](/support/inquiry)にて以下の事項を記述の上、ご連絡ください。。  
```
以上で修正しました。

2022-05-11 10:09 UTC, Omuretsu commented on server/profiles.md
> +|![Ekusas83](https://storage.jaoafa.com/b7e612706c25b7bb967dc6faa7ab63ce.png)|Ekusas|Ekusas83|[@ekusas55000](https://twitter.com/ekusas55000)|[ekusas#8352](https://discord.com/users/18937705495579852
スラッシュかカンマぐらいかなと思います。置き換えるなら。

2022-05-11 10:11 UTC, Omuretsu commented on server/specifications.md
> +(サーバに一度もログインしたことのない状態、サーバがオフライン（停止中）の状態での投票は補填できませんのでご注意ください。)
```suggestion
(サーバに一度もログインしたことのない状態、サーバがオフラインの状態での投票は補填できませんのでご注意ください。)
```
修正（加筆部分を削除）しました。

2022-05-11 10:36 UTC, book000 commented on support/faq.md
> +サーバへの再参加やMinecraftクライアントの再起動を行っても解決しない場合は、[公式Discordサーバ](/blog/join-discord) `#support`チャンネルや[お問い合わせフォーム](https://forms.gle/Rpj1ZV76p2NsdWMK6)を用いて、以下の内容を記述した上で運営まで問い合わせを行ってください。
句点が二つ入っちゃってるので、適用の際はご注意あれ

2022-05-15 20:23 UTC, book000 commented
修正終わったらDiscordで一報ください。

2022-05-18 14:39 UTC, Omuretsu commented on server/profiles.md
> +|![Ekusas83](https://storage.jaoafa.com/b7e612706c25b7bb967dc6faa7ab63ce.png)|Ekusas|Ekusas83|[@ekusas55000](https://twitter.com/ekusas55000)|[ekusas#8352](https://discord.com/users/18937705495579852
#145 で管理をします。

2022-05-18 14:56 UTC, book000 commented
メモ: いくつかの更新を分離してプルリクエストを出すらしいので、それらが終わり次第こちらをマージします。

2022-05-18 14:57 UTC, Omuretsu commented on blog/limited-verified.md
> +- [Discord](https://wiki.jaoafa.com/jMS_Gamers_Club)において、次の理由のうちどれかにより、アカウントを作成できない利用者であること
#146 で管理をします。

2022-05-18 15:41 UTC, Omuretsu commented on server/guidelines/broadcasts.md
> +また、他人の建造物を自らが作ったと偽ってスクリーンショットを公開する、といった行為もお控えください。
#147 で管理をします。

2022-05-18 16:08 UTC, Omuretsu commented on server/guidelines/communications.md
> +当サーバの運営はDiscord内のサーバを運営するに当たり、Discord公式が定める利用規約とガイドラインに同意しています。
#149 で管理します。

2022-05-18 17:48 UTC, Omuretsu commented
> メモ: いくつかの更新を分離してプルリクエストを出すらしいので、それらが終わり次第こちらをマージします。

以下のプルリクエストがマージされ次第、このプルリクエスト( #144 )をマージお願いします。
#146 #147 #149

2022-05-22 16:30 UTC, book000 commented
めも: Markdown header checkが落ちてるのはバグなので無視していいです（`upstream/main` からマージしたことで更新ファイル一覧の取得がおかしくなってるだけ）

2022-05-22 16:58 UTC, minhero-exp approved these changes

2022-05-22 17:02 UTC, book000 approved these changes

2022-05-22 22:02 UTC, Hiratake approved these changes

2022-05-22 23:16 UTC, merged