文章の修正
jaoafa/jaoweb-docs pull request #146
Opened 2022-05-18 14:56 UTC by Omuretsu

「次のうちのどれかにより」
→「次のうちのいずれかにより」

2022-05-18 14:59 UTC, book000 requested changes

2022-05-18 14:59 UTC, book000 commented on blog/limited-verified.md
> +- [Discord](https://wiki.jaoafa.com/jMS_Gamers_Club)において、次の理由のうちのいずれかによりアカウントを作成できない利用者であること
```suggestion
- [Discord](https://wiki.jaoafa.com/jMS_Gamers_Club)において、次の理由のいずれかによりアカウントを作成できない利用者であること
```

2022-05-18 15:00 UTC, book000 approved these changes

2022-05-22 08:29 UTC, Hiratake approved these changes

2022-05-22 08:31 UTC, merged