「撮影・動画配信に関するガイドライン」における、基本方針の策定
jaoafa/jaoweb-docs pull request #147
Opened 2022-05-18 15:40 UTC by Omuretsu

・今まで「静止画」「動画」に分けて記述していた配信方針について、共通の方針項目を「基本方針」としてまとめました。
・それに伴い、一部文章の修正を行いました。

2022-05-18 15:50 UTC, Omuretsu commented
関連PullRequest: #144 
関連Issue: #148

2022-05-18 15:54 UTC, book000 requested changes

2022-05-18 15:54 UTC, book000 commented on server/guidelines/broadcasts.md
> +    1. 建築物を制作したユーザが、その建築物を撮影をしないよう求めている場合は、それらが映り込まないようにしてください。
```suggestion
    1. 建築物を制作したユーザが、その建築物の撮影をしないよう求めている場合は、それらが映り込まないようにしてください。
```

2022-05-18 15:54 UTC, book000 commented on server/guidelines/broadcasts.md
> +- 外部サービスへスクリーンショットや動画を投稿する際には、サーバ名を明記することやハッシュタグをつける（公式ハッシュタグ： `#jaoafa` ）ことで、当サーバにて撮影されたことがわかるようにしてください。
```suggestion
- 外部サービスへスクリーンショットや動画を投稿する際には、サーバ名を明記することやハッシュタグをつける（公式ハッシュタグ： `#jaoafa`）ことで、当サーバにて撮影されたことがわかるようにしてください。
```

2022-05-18 15:54 UTC, book000 commented on server/guidelines/broadcasts.md
> +また、特に動画を撮影する際には、事前にサーバ内や公式Discordサーバの `#announcement` チャンネル等で、「撮影や配信を行う旨」を告知するようお願いいたします。
```suggestion
また、撮影・配信を行う際には、事前にサーバ内や公式Discordサーバの `#announcement` チャンネル等で、「撮影や配信を行う旨」を告知するようお願いいたします。
```

2022-05-18 15:54 UTC, book000 commented on server/guidelines/broadcasts.md
> +撮影した動画を外部サービスへ投稿・配信する場合は、あらかじめ運営チームへの申請をお願いしております。
```suggestion
外部サービスで動画投稿や配信を行う場合は、あらかじめ運営チームへの申請をお願いしております。  
```

2022-05-18 15:58 UTC, book000 approved these changes

2022-05-18 22:56 UTC, yuuahp approved these changes

2022-05-19 14:18 UTC, lncongruence reviewed
当サーバ内では、**私的な利用を目的とした**スクリーンショット（静止画）の撮影、および動画の撮影を**容認**しています。

まるで、「私的な利用を目的としたスクリーンショット（静止画）の撮影、および動画の撮影」という行為は一般的に(or 当鯖にとって)悪事であるが、当鯖はそれを特別に許可している……と主張しているかのように解釈されかねないので、このような項目を書く場合は「～ および動画の撮影を**制限することはありません**」「～および動画の撮影に対し、**制約を課しません**」といった感じの表現に変えるべきかも。

それ以降も「私的な撮影は可能」「jao鯖内で配信は可能」といった内容があちこちに分散されていて、ガイドラインを読んだ時に推奨されること、されないことを把握するのが大変なので、推奨されること・されないことを最初の方に箇条書きで並べてもいいのかなあってお気持ち。

2022-05-20 07:23 UTC, Omuretsu commented on server/guidelines/broadcasts.md
> +当サーバ内では、外部サービスへの投稿などを目的としない、私的利用を目的とした撮影は運営の許諾なしに行っていただけます。
https://github.com/jaoafa/jaoweb-docs/pull/147/commits/1354e35bac91f4ce37d76f7b50af51b39ac9a93a で修正しました。

2022-05-20 07:26 UTC, Omuretsu commented on server/guidelines/broadcasts.md
> +- 当サーバ内では、**私的な利用を目的とした**スクリーンショット（静止画）の撮影、および動画の撮影を**容認**しています。
https://github.com/jaoafa/jaoweb-docs/pull/147/commits/9cdadf4f15e328bbbb383330e7649cfac8fd6375 で修正しました。

2022-05-20 08:11 UTC, Omuretsu commented
> 当サーバ内では、**私的な利用を目的とした**スクリーンショット（静止画）の撮影、および動画の撮影を**容認**しています。
> 
> まるで、「私的な利用を目的としたスクリーンショット（静止画）の撮影、および動画の撮影」という行為は一般的に(or 当鯖にとって)悪事であるが、当鯖はそれを特別に許可している……と主張しているかのように解釈されかねないので、このような項目を書く場合は「～ および動画の撮影を**制限することはありません**」「～および動画の撮影に対し、**制約を課しません**」といった感じの表現に変えるべきかも。
> 
> それ以降も「私的な撮影は可能」「jao鯖内で配信は可能」といった内容があちこちに分散されていて、ガイドラインを読んだ時に推奨されること、されないことを把握するのが大変なので、推奨されること・されないことを最初の方に箇条書きで並べてもいいのかなあってお気持ち。
> 
> (今更変更しろはアレなので普通にｺﾒﾝﾖだけ)

@lncongruence 
取り急ぎ、表現に関しては https://github.com/jaoafa/jaoweb-docs/pull/147/commits/17607f06fee6d5ee6075ff8cab92946b27083e4e で修正をしました。
方針自体のあり方などについては #148 かDiscordにて話し合いましょう。

2022-05-22 08:54 UTC, Hiratake approved these changes

2022-05-22 16:06 UTC, book000 approved these changes

2022-05-22 16:07 UTC, kohonayoshi approved these changes

2022-05-22 16:09 UTC, merged