Discordの二段階認証を解説するブログ記事において、情報の更新
jaoafa/jaoweb-docs pull request #150
Opened 2022-05-18 16:23 UTC by Omuretsu

表題の通りです。

2022-05-18 16:25 UTC, book000 requested changes

2022-05-18 16:25 UTC, book000 commented on blog/discord-two-factor.md
> +Discordのアカウントを、**不正アクセスから守るため**です。
```suggestion
Discordのアカウントを、**不正アクセスから守るため**です。  
```

2022-05-19 04:42 UTC, minhero-exp approved these changes

2022-05-22 08:23 UTC, Hiratake requested changes

2022-05-22 08:23 UTC, Hiratake commented on blog/discord-two-factor.md
> +MacOS向けのデスクトップアプリでも設定が可能であるほか、2022年5月19日現在ではiOS版アプリからでも設定ができることを確認しています。
mは小文字かも。
https://ja.wikipedia.org/wiki/macOS

```suggestion
macOS向けのデスクトップアプリでも設定が可能であるほか、2022年5月19日現在ではiOS版アプリからでも設定ができることを確認しています。
```

2022-05-22 08:33 UTC, Hiratake approved these changes

2022-05-22 12:47 UTC, book000 approved these changes

2022-05-22 12:47 UTC, merged