「サーバ停止のお知らせ」の記事について、情報の更新
jaoafa/jaoweb-docs pull request #153
Opened 2022-05-18 17:40 UTC by Omuretsu

「サーバのサービス提供が既に再開されている旨」を追記。

2022-05-18 18:00 UTC, book000 approved these changes

2022-05-22 08:19 UTC, Hiratake requested changes

2022-05-22 08:19 UTC, Hiratake commented on blog/202112-server-stop.md
> +*このページは2021年12月11日時点での情報をもとに執筆したものです。*
これ斜めな文字になってるのはなにゆえ？

2022-05-22 08:19 UTC, Hiratake commented on blog/202112-server-stop.md
> +*このページは2021年12月11日時点での情報をもとに執筆したものです。*
```suggestion
**このページは2021年12月11日時点での情報をもとに執筆したものです。**  
```

2022-05-22 08:19 UTC, Hiratake commented on blog/202112-server-stop.md
> +*2022年5月19日現在、<span style="color: red">サーバのサービス提供は再開されています</span>。*
```suggestion
**2022年5月19日現在、<span style="color: red">サーバのサービス提供は再開されています</span>。**
```

2022-05-22 08:34 UTC, Hiratake approved these changes

2022-05-22 08:35 UTC, merged