Limited Verifiedについて、各種規則などを明文化
jaoafa/jaoweb-docs pull request #157
Opened 2022-06-01 09:24 UTC by Omuretsu

【Limited Verifiedの解説ページ】
・descriptionタグを追加
・継続申請の方法を明文化
・その他軽微な修正

【自治体方針】
・Limited Verifiedが自治体申請を行えない旨を明文化。

2022-06-01 13:17 UTC, book000 requested changes

2022-06-01 13:17 UTC, book000 commented on blog/limited-verified.md
> +3. [権限グループ「Limited Verified」付与申請フォーム](https://docs.google.com/forms/d/e/1FAIpQLScc_sLdQrN7WeHGPpc8uSTpyJ-7yiPyie_NBDWNoU69zfmCNQ/viewform)にアクセスしてください。
```suggestion
3. [権限グループ「Limited Verified」関連申請フォーム](https://docs.google.com/forms/d/e/1FAIpQLScc_sLdQrN7WeHGPpc8uSTpyJ-7yiPyie_NBDWNoU69zfmCNQ/viewform)にアクセスしてください。
```

2022-06-01 13:17 UTC, book000 commented on blog/limited-verified.md
>  - 自治体関連の申請などは現在専用フォームを制作しています。フォームが完成するまで、Limited Verified権限の利用者は自治体申請ができません。
Clubjaoafaの実装によってDiscordアカウントがなくても(Verifiedであれば)申請できる…はずなのですが、まあ全部の通知がDiscordで飛ぶことを考えると無理ですね…

2022-06-01 13:17 UTC, book000 commented on blog/limited-verified.md
> +[権限グループ「Limited Verified」付与申請フォーム](https://docs.google.com/forms/d/e/1FAIpQLScc_sLdQrN7WeHGPpc8uSTpyJ-7yiPyie_NBDWNoU69zfmCNQ/viewform)へアクセスし、指定された項目を記述の上送信してください。
```suggestion
[権限グループ「Limited Verified」関連申請フォーム](https://docs.google.com/forms/d/e/1FAIpQLScc_sLdQrN7WeHGPpc8uSTpyJ-7yiPyie_NBDWNoU69zfmCNQ/viewform)へアクセスし、指定された項目を記述の上送信してください。  
```

2022-06-01 13:17 UTC, book000 commented on server/guidelines/cities.md
> +  (自治体管理者が公式Discordサーバから退出しVerified権限を失った場合、同時に所有している自治体の所有権が剥奪(取り消し)されます。)
これ、もともとの文章も問題っぽいですがかっこの中にかっこを入れるのは微妙かも。周りのかっこ外してもいいんじゃないかな

2022-06-01 13:17 UTC, book000 commented on blog/limited-verified.md
>  - 自治体関連の申請などは現在専用フォームを制作しています。フォームが完成するまで、Limited Verified権限の利用者は自治体申請ができません。
「現在専用フォームを制作」していないので、根本的に(将来的にも)LVが自治体申請を行えるようになる予定はありません。

2022-06-01 13:17 UTC, book000 commented on server/guidelines/cities.md
> +- [Limited Verified権限](/blog/limited-verified)を付与されたユーザについては、自治体に関する各種申請は行なえません。
```suggestion
- [Limited Verified権限](/blog/limited-verified)を付与されたユーザについては、自治体に関する各種申請は行えません。  
```

参照: https://www.mitsumura-tosho.co.jp/webmaga/kotoba/detail19.html  
どっちでもいいみたいですが、「～う」で統一しましょうか

2022-06-01 13:17 UTC, book000 commented on server/guidelines/cities.md
> +
この改行はなんのために入れましたか？

2022-06-01 14:45 UTC, Omuretsu commented on server/guidelines/cities.md
> +   現在申請に関するシステムが、Limited verified権限に対応していないためです。
https://github.com/jaoafa/jaoweb-docs/pull/157/commits/cf308b2cb42ecf518c523aa646a505536c97809c で修正しました。

2022-06-02 04:01 UTC, book000 commented on blog/limited-verified.md
>  - 自治体関連の申請などは現在専用フォームを制作しています。フォームが完成するまで、Limited Verified権限の利用者は自治体申請ができません。
:+1:

2022-06-02 04:50 UTC, book000 commented on server/guidelines/cities.md
> +
Markdownの仕様上、リストに対して純粋に改行を入れただけでは空行にならない（プレビューを参考）なので、h3タグを入れるか水平線(`---`)をいれるかして明示的に空けたほうがよさそうです。
ちなみに、改行を入れるとリスト全項目の間が空く（HTML的におかしくなる）のでどうあれやめたほうがいいかと思います…

2022-06-02 05:44 UTC, book000 commented on server/guidelines/cities.md
> +
HTML的におかしくなるかはMarkdownからHTMLに変換するコンバーターによるかもしれません。とはいえ、たぶんオムレツが思っている通りの挙動（リストの分割）はできていないように見えるので別の方法（例: h4挿入）などをしたほうがよさげです

2022-06-02 06:05 UTC, Omuretsu commented on server/guidelines/cities.md
> +
https://github.com/jaoafa/jaoweb-docs/pull/157/commits/cd519dd10757b8ab26d7af8dc2dc60de2d32560c で修正しました。

2022-06-02 07:40 UTC, book000 commented
ちなみに、変更後にわざわざレビュー刺し直さなくても大丈夫ですよ

2022-06-03 12:33 UTC, minhero-exp approved these changes

2022-06-03 12:37 UTC, book000 requested changes

2022-06-03 12:37 UTC, book000 commented on server/guidelines/cities.md
> +- 申請の受領確認と認否結果については、[公式Discordサーバ](/blog/join-discord)の`#city_request`チャンネルにて通知します。
```suggestion
- 申請の受付通知と認否結果の通知については、[公式Discordサーバ](/blog/join-discord)の`#city_request`チャンネルにて行います。
```

申請って「受領」するもの…？受領ってオカネとかそっちのイメージがあるけど

2022-06-03 12:37 UTC, book000 commented on server/guidelines/cities.md
> +- 申請の受領確認と認否結果については、[公式Discordサーバ](/blog/join-discord)の`#city_request`チャンネルにて通知します。
```suggestion
- 申請の受付通知と認否結果の通知については、[公式Discordサーバ](/blog/join-discord)の`#city_request`チャンネルにて行います。
```

2022-06-03 12:37 UTC, book000 commented on server/guidelines/cities.md
> +楽しくない場所からは人がいなくなり、結果として消滅します。私達運営も仕事でやっているわけではないですし、離れても食べていけなくなるわけではありません。
```suggestion
楽しくない場所からは人がいなくなり、結果として消滅します。私達運営も仕事でやっているわけではないですし、離れても食べていけなくなるわけではありません。  
```

2022-06-03 12:38 UTC, book000 commented
ヒラタケはレビュアー差し直し前にapproveしているので、私がapproveしたらマージします

2022-06-03 12:39 UTC, book000 approved these changes

2022-06-03 12:40 UTC, Hiratake approved these changes

2022-06-03 12:41 UTC, merged