自治体ガイドラインの修正
jaoafa/jaoweb-docs pull request #160
Opened 2022-06-03 13:33 UTC by Omuretsu

1.申請の取り下げについて
新規申請・範囲更新における「申請の取り下げ」について、 support での取り下げ申請を「申請者本人からのみ受け付ける」旨の追記。

2.自治体の削除申請について
「自治体を削除する方法（自治体登録解除）」において、「自治体の管理者本人からのみ申請を受け付ける」旨の追記。
および凡例（テンプレート）において、MinecraftIDを記載するよう追加。

2022-06-03 13:38 UTC, book000 requested changes

2022-06-03 13:38 UTC, book000 commented on server/guidelines/cities.md
> +- 取り下げが行われた時点で、運営内審議を終了します。
`自治体登録解除 登録解除申請の凡例 (テンプレート)` の本文章の位置とここでズレてる（コードブロックの上にあるべきな気がする）ので、直したほうがよさそうな

2022-06-03 14:41 UTC, Omuretsu commented on server/guidelines/cities.md
> +- 取り下げが行われた時点で、運営内審議を終了します。
https://github.com/jaoafa/jaoweb-docs/pull/160/commits/3c786f100ea13aea7a320b3a0f06b83034703c17 で修正しました。

2022-06-03 15:53 UTC, book000 approved these changes

2022-06-04 15:54 UTC, Hiratake approved these changes

2022-06-04 15:54 UTC, merged