「自治体方針」について、文章の修正
jaoafa/jaoweb-docs pull request #161
Opened 2022-06-04 23:38 UTC by Omuretsu

1.「基本方針」の中に「自治体名称や概要についての基本方針」カテゴリを追加

2.「基本方針」の整理、「自治体付与についての基本方針」の一部を「自治体名称や概要についての基本方針」に移動、「権限付与についての基本方針」「権限剥奪についての基本方針」を追加

3.「自治体名称や概要についての基本方針」に文言を追加

4.「自治体情報変更申請」についての説明文を追加

5.自治体の所有権失効など「3ヶ月未ログイン時の対応」についての条文が一切ないため追記

6.その他軽微な修正など

関連Issue: #159

2022-06-04 23:53 UTC, kohonayoshi approved these changes

2022-06-05 00:33 UTC, Omuretsu commented
同時に #meeting_vote で投票を行っているので、そちらもよろしくおねがいします。

2022-06-05 01:42 UTC, minhero-exp approved these changes

2022-06-05 05:33 UTC, Hiratake approved these changes

2022-06-05 12:16 UTC, book000 requested changes
別プロジェクトを進めており後回しにしていました、遅れてすみません。よろしくお願いします。

2022-06-05 12:16 UTC, book000 commented on server/guidelines/cities.md
> +- 自治体名称（英語） および WorldGuardの保護名
```suggestion
- WorldGuardの保護名
```

2022-06-06 05:55 UTC, book000 approved these changes

2022-06-07 09:55 UTC, yuuahp approved these changes

2022-06-07 10:37 UTC, merged