club.jaoafa.comのパスワードを忘れた際の、対処法を追記
jaoafa/jaoweb-docs pull request #167
Opened 2022-07-20 06:01 UTC by Omuretsu

表題のとおりです。
自治体申請について関連するページを編集しています。

close #166

2022-07-20 06:03 UTC, Omuretsu commented on blog/request-cities.md
> +[jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#jMS Minecraft Server Members Club のパスワードを忘れてしまった)をご確認ください。
```
[こちら](/support/faq/#jMS Minecraft Server Members Club のパスワードを忘れてしまった)をご確認ください。
```
ここのリンクが正しく作動するか、確認をお願いしたいです。

2022-07-20 06:03 UTC, Omuretsu commented on server/guidelines/cities.md
> +- [jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#jMS Minecraft Server Members Club のパスワードを忘れてしまった)をご確認ください。
```
[こちら](/support/faq/#jMS Minecraft Server Members Club のパスワードを忘れてしまった)をご確認ください。
```
ここのリンクが正しく作動するか、確認をお願いしたいです。

2022-07-20 07:24 UTC, book000 commented on blog/request-cities.md
> +[jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#jMS Minecraft Server Members Club のパスワードを忘れてしまった)をご確認ください。
![image](https://user-images.githubusercontent.com/8929706/179921883-63f03dcb-aeae-440f-b9a5-ced3f4cec32d.png)

だめっぽそうです

2022-07-20 07:24 UTC, book000 commented on server/guidelines/cities.md
> +- [jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#jMS Minecraft Server Members Club のパスワードを忘れてしまった)をご確認ください。
こちらも同じくだめっぽそうです

2022-07-20 07:53 UTC, book000 requested changes

2022-07-20 07:53 UTC, book000 commented on blog/request-cities.md
> +[jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#jMS Minecraft Server Members Club のパスワードを忘れてしまった)をご確認ください。
URLにおける `#` (フラグメント識別子)は要素のID名を渡すことでジャンプするようになっているので、ブラウザのインスペクタツール（Chrome: `右クリック->検証` / Firefox: `右クリック -> 調査`）から該当項目のIDを調べる必要があります。
![image](https://user-images.githubusercontent.com/8929706/179927057-605fda99-f2d6-471f-8793-4c40679ee973.png)

この場合は `id="jms-minecraft-server-members-club-のパスワードを忘れてしまった"` なので `#jms-minecraft-server-members-club-のパスワードを忘れてしまった` が正解です。

2022-07-20 07:53 UTC, book000 commented on support/faq.md
> +## jMS Minecraft Server Members Club のパスワードを忘れてしまった
```suggestion
## Q. jMS Minecraft Server Members Club のパスワードを忘れてしまった
```

2022-07-20 07:53 UTC, book000 commented on blog/request-cities.md
> +[jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#jMS Minecraft Server Members Club のパスワードを忘れてしまった)をご確認ください。
まあ、すべての文字を小文字にしたうえでスペースをハイフンに置き換える、がたぶんjaowebにおけるアンカーの設定なんだと思います

2022-07-20 07:53 UTC, book000 commented on support/faq.md
> +アカウントの復旧を希望される方は、その旨とMinecraftIDを、[公式Discordサーバ](/blog/join-discord) `#support`チャンネルにてお知らせください。
```suggestion
したがってパスワードを忘れた場合は、運営によるアカウントの削除処理が必要となります（削除後に再登録していただきます）。  
アカウントの削除を希望される方は、その旨とMinecraftIDを、[公式Discordサーバ](/blog/join-discord) `#support`チャンネルにてお知らせください。
```

2022-07-20 07:57 UTC, Omuretsu commented on blog/request-cities.md
> +[jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#jMS Minecraft Server Members Club のパスワードを忘れてしまった)をご確認ください。
```suggestion
[jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#jMS-Minecraft-Server-Members-Club-のパスワードを忘れてしまった)をご確認ください。
```

2022-07-20 07:58 UTC, Omuretsu commented on server/guidelines/cities.md
> +- [jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#jMS Minecraft Server Members Club のパスワードを忘れてしまった)をご確認ください。
```suggestion
- [jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#jMS-Minecraft-Server-Members-Club-のパスワードを忘れてしまった)をご確認ください。
```

2022-07-20 11:18 UTC, book000 requested changes

2022-07-20 11:18 UTC, book000 commented on server/guidelines/cities.md
> +- [jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#jMS-Minecraft-Server-Members-Club-のパスワードを忘れてしまった)をご確認ください。
`Q. ` を最初に入れたので、ここも修正する必要があります。

```suggestion
- [jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#q-jms-minecraft-server-members-club-のパスワードを忘れてしまった)をご確認ください。
```

2022-07-20 11:18 UTC, book000 commented on blog/request-cities.md
> +[jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#jMS-Minecraft-Server-Members-Club-のパスワードを忘れてしまった)をご確認ください。
```suggestion
[jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちら](/support/faq/#q-jms-minecraft-server-members-club-のパスワードを忘れてしまった)をご確認ください。
```

2022-07-20 13:13 UTC, book000 approved these changes

2022-07-28 11:30 UTC, minhero-exp approved these changes

2022-07-28 12:25 UTC, Hiratake approved these changes

2022-07-28 12:27 UTC, merged