なんかいろいろあったけど、FAQの質問を大まかに分類
jaoafa/jaoweb-docs pull request #172
Opened 2022-08-02 13:28 UTC by lncongruence

などと供述しており、容疑を認めている模様です。

FAQの質問一覧がなんかごちゃっているように感じたので、各質問にマイクラ鯖に入る前、サーバ内、建築、コミュニティ、システム、Webサイトといった大分類のようなものを作り、目的の質問を見つけやすくしようと試みました。

また、「ログインできない」の質問の回答をキック時に表示されるメッセージに置き換え、ユーザが参照しやすいようにしました(つもり)。

2022-08-02 14:22 UTC, Omuretsu requested changes

2022-08-02 14:22 UTC, Omuretsu commented on support/faq.md
> +- **"あなたは以下のアカウントで既にログインされたことがあるようです。(1)" と表示される**
```suggestion
- **"あなたは以下のアカウントで既にログインされたことがあるようです。(1)" と表示される  **
```
改行した方がよいと思われます。

2022-08-02 14:22 UTC, Omuretsu commented on support/faq.md
> +- **"海外からのログインと判定されました。当サーバでは、日本国外からのログインを禁止しています。" と表示される**
```suggestion
- **"海外からのログインと判定されました。当サーバでは、日本国外からのログインを禁止しています。" と表示される**  
```
改行した方がよいと思われます。

2022-08-02 14:22 UTC, Omuretsu commented on support/faq.md
> +- **"このサーバーへのアクセスは禁止されています" と表示される**
```suggestion
- **"このサーバーへのアクセスは禁止されています" と表示される**  
```
改行した方がよいと思われます。

2022-08-02 14:22 UTC, Omuretsu commented on support/faq.md
> +## Minecraft鯖へのログインまでによくあるご質問
```suggestion
## Minecraftサーバへのログインまでによくあるご質問
```

2022-08-02 14:22 UTC, Omuretsu commented on support/faq.md
> +当該権限を付与されたプレイヤーはWorldEditの選択ツール(木の斧)で範囲指定したのち、`/chuocity claim [保護の名前]`とコマンド入力することで範囲保護を作成することができ、この範囲内で自由にWorldEditをご利用になれます。
```suggestion
当該権限を付与されたプレイヤーはWorldEditの選択ツール(木の斧)で範囲指定したのち、`/chuocity claim [保護の名前]`とコマンド入力することで範囲保護を作成することができ、この範囲内で自由にWorldEditをご利用になれます。  
詳しい権限の付与方針については、[こちら](/server/policies/permissions)をご確認ください。  
```

2022-08-02 14:22 UTC, Omuretsu commented on support/faq.md
>  詳しくは[個別記事](/blog/limited-verified)をご確認ください。
```
当サーバでは、MinecraftアカウントとDiscordアカウントを連携したユーザに対して、WorldEditなどの利用が可能となる`Verified`権限を付与しています。  
 しかし[Discord公式が定めるサービス利用規約](https://discord.com/terms#親および保護者の年齢の要件と責任)を根拠に、13歳未満のユーザが公式Discordサーバを利用することを禁止しています。
 その他の事由も含めDiscordが利用できないユーザがいることを鑑み、代替措置として別途申請を行ったユーザは、Verified権限と同じ権限を得ることができます。  
 詳しくは[個別記事](/blog/limited-verified)をご確認ください。
```
84~87行目（このレビューの執筆時）に同じ旨を記述しているので、ここは不要だと思われます。

2022-08-02 14:44 UTC, book000 requested changes

2022-08-02 14:44 UTC, book000 commented on support/faq.md
> +- **"あなたは以下のアカウントで既にログインされたことがあるようです。(1)" と表示される**
```suggestion
- **"あなたは以下のアカウントで既にログインをされたことがあるようです。" と表示される**  
```

2022-08-02 14:51 UTC, book000 commented on support/faq.md
> +- **"あなたは以下のアカウントで既にログインされたことがあるようです。(1)" と表示される**
`**` より前にスペース二つ入れるとたぶん挙動おかしくなるので、末尾に入れる必要があります（私のほうでサジェスト出しました）

2022-08-02 14:54 UTC, book000 commented on support/faq.md
> +### チャットができない
```suggestion
### Q. チャットができない
```

2022-08-02 15:08 UTC, minhero-exp commented on support/faq.md
> +当該権限を付与されたプレイヤーはWorldEditの選択ツール(木の斧)で範囲指定したのち、`/chuocity claim [保護の名前]`とコマンド入力することで範囲保護を作成することができ、この範囲内で自由にWorldEditをご利用になれます。
そうなんですか？権限グループをVerifiedにして検証してみたところ、中央市内であれば自分の保護のない場所でもWorldEditを使用できるようです。

2022-08-02 15:08 UTC, minhero-exp commented on support/faq.md
> +### Q. jMS Minecraft Server Members Club のパスワードを忘れてしまった
```suggestion
### Q. jao Members Club のパスワードを忘れてしまった
```

2022-08-02 15:08 UTC, minhero-exp commented on support/faq.md
> +[jMS Minecraft Server Members Club](https://club.jaoafa.com/)では現在、パスワードの再発行機能は提供しておりません。
```suggestion
[jao Members Club](https://club.jaoafa.com/)では現在、パスワードの再発行機能は提供しておりません。  
```

2022-08-02 15:08 UTC, minhero-exp commented on support/faq.md
> +[jMS Minecraft Server Members Club](https://club.jaoafa.com/)では現在、パスワードの再発行機能は提供しておりません。
正式名称はこうだったはず… どちらにしろ、**jMS** Minecraft Serverはおかしいかも。

2022-08-02 15:10 UTC, lncongruence commented on support/faq.md
>  詳しくは[個別記事](/blog/limited-verified)をご確認ください。
84~87行目(Q. MinecraftIDを変更しても大丈夫？)と129~132行目(Q. 13歳未満のため公式Discordサーバへアクセスできないが、WorldEditを利用したい。)は質問内容が大きく異なります。

質問別に回答を記述する形式のページですので、何か問題があったときにその解決策を確認する際、異なる内容の質問にリンクされるような状態になるのは不便かと思われますので、同じ内容を記述しています。

2022-08-02 15:16 UTC, Omuretsu commented on support/faq.md
>  詳しくは[個別記事](/blog/limited-verified)をご確認ください。
理解しました。

2022-08-02 15:19 UTC, book000 commented on support/faq.md
> +[jMS Minecraft Server Members Club](https://club.jaoafa.com/)では現在、パスワードの再発行機能は提供しておりません。
Webサイトのタイトルは `jao Member Club` 、GitHubの説明文は `jao Minecraft Server Members Club` です。まあWebサイトのタイトルに準じていいと思います。

2022-08-02 15:27 UTC, book000 commented on support/faq.md
> +- **"あなたは以下のアカウントで既にログインされたことがあるようです。(1)" と表示される**
私のほうのサジェストが適用されたのでresolveします

2022-08-02 15:34 UTC, book000 commented on support/faq.md
> +当該権限を付与されたプレイヤーはWorldEditの選択ツール(木の斧)で範囲指定したのち、`/chuocity claim [保護の名前]`とコマンド入力することで範囲保護を作成することができ、この範囲内で自由にWorldEditをご利用になれます。
まあ、うーん。保護ナシでWE使えるなら順当にWE使う人にとってはいいのかも…。
荒らし対策としてはうーんですけど。

2022-08-02 15:51 UTC, Omuretsu approved these changes

2022-08-02 15:54 UTC, book000 commented on support/faq.md
> +当該権限を付与されたプレイヤーはWorldEditの選択ツール(木の斧)で範囲指定したのち、`/chuocity claim [保護の名前]`とコマンド入力することで範囲保護を作成することができ、この範囲内で自由にWorldEditをご利用になれます。
とりあえず、このPRでは当該行を消して別issueで対応する方向性で。

2022-08-03 02:40 UTC, Hiratake requested changes

2022-08-03 02:40 UTC, Hiratake commented on support/faq.md
> +  あなたは当MinecraftサーバからBan(アクセスの禁止)されています。
他の箇所が「当サーバ」になってるので、表現を合わせたほうがよきかも。
```suggestion
  あなたは当サーバからBan(アクセスの禁止)されています。
```

2022-08-03 02:40 UTC, Hiratake commented on support/faq.md
> +ほぼすべてのシステムがUUID(そのプレイヤー固定のID)を使用して管理されているため、とくに問題はありません。
細かいとこですが、「システムが管理されている」わけではないので、変えたほうがよきかも。
```suggestion
プレイヤーの情報は、MinecraftIDではなくUUID（変更することができない固定のID）を用いて管理しています。MinecraftIDをご変更された場合でも、これまで通り当サーバをご利用いただけます。  
```

2022-08-03 02:40 UTC, Hiratake commented on support/faq.md
> +ほぼすべてのシステムがUUID(そのプレイヤー固定のID)を使用して管理されているため、とくに問題はありません。
「プレイヤー」と「ユーザ」のどっち使えばいいかわがんね

2022-08-03 02:46 UTC, book000 commented on support/faq.md
> +ほぼすべてのシステムがUUID(そのプレイヤー固定のID)を使用して管理されているため、とくに問題はありません。
個人的には、Minecraftで**遊ぶ**人 = `プレイヤー` (Minecraft **player**)・その他サービスを**使う**人 = `ユーザ` (Service **user**)で考えてるけど、完全統一まではしてないかしらねえ

2022-08-03 02:48 UTC, book000 approved these changes
とりあえず上がってる問題が解決されたら私はオッケーです

2022-08-03 02:48 UTC, Hiratake commented on support/faq.md
> +ほぼすべてのシステムがUUID(そのプレイヤー固定のID)を使用して管理されているため、とくに問題はありません。
ふみゅ
まあその辺の統一は色々確認して別のPRでやる感じかねえ

2022-08-06 14:42 UTC, Omuretsu commented on support/faq.md
> +ほぼすべてのシステムがUUID(そのプレイヤー固定のID)を使用して管理されているため、とくに問題はありません。
とりあえず #174 を立てました。

2022-08-12 11:52 UTC, Omuretsu commented on support/faq.md
> +ほぼすべてのシステムがUUID(そのプレイヤー固定のID)を使用して管理されているため、とくに問題はありません。
```suggestion
プレイヤーの情報は、MinecraftIDではなくUUID（変更することができない固定のID）を用いて管理しています。  
MinecraftIDを変更された場合でも、これまで通り当サーバをご利用いただけます。 
```
[ヒラタケさんのsuggest](https://github.com/jaoafa/jaoweb-docs/pull/172#discussion_r936182938)について、「ご変更された場合」だと二重敬語で違和感があるので、修正を提案します。

2022-08-12 12:09 UTC, Hiratake commented on support/faq.md
> +ほぼすべてのシステムがUUID(そのプレイヤー固定のID)を使用して管理されているため、とくに問題はありません。
一応二重敬語に該当しないかどうかを調べた上でサジェストしていましたが、間違ったかもですね。
仮に問題なかったとしても、他の人が見て違和感がない書き方のほうがよきですね。
なんかいい感じにしてもろて。

2022-08-12 12:21 UTC, Omuretsu requested changes
ということで、この一連の流れについて対応をよろしくお願いいたします。
https://github.com/jaoafa/jaoweb-docs/pull/172#discussion_r936182938

2022-08-13 22:42 UTC, lncongruence commented on support/faq.md
> +ほぼすべてのシステムがUUID(そのプレイヤー固定のID)を使用して管理されているため、とくに問題はありません。
ここはあくまでゲームのコミュニティサーバのWebサイトで、普段から敬語の文章を読み慣れていないような年齢層の利用者が大半を占めていることでしょう。
なので、尊敬語や謙譲語をしっかり盛り込んでしっかり敬意を示すより、丁寧語とほんの少しの普段使い(?)される程度の尊敬謙譲語のみ使うくらいの文章のほうが適切なのかなあと思いました。
オムレツさんのsuggestを取り込みます。

2022-08-13 22:46 UTC, book000 requested changes

2022-08-13 22:46 UTC, book000 commented on support/faq.md
> +MinecraftIDを変更された場合でも、これまで通り当サーバをご利用いただけます。
改行する場合は末尾に2つのスペースが必要です。
```suggestion
MinecraftIDを変更された場合でも、これまで通り当サーバをご利用いただけます。  
```

2022-08-13 22:51 UTC, book000 approved these changes

2022-08-13 22:51 UTC, Omuretsu approved these changes

2022-08-14 01:18 UTC, Hiratake approved these changes

2022-08-14 01:20 UTC, book000 commented
ちょっと、私たちだけでは見落としてる部分ありそうで怖いのでえきぱ氏にもレビュアー刺させてください

2022-08-14 01:27 UTC, minhero-exp commented on support/faq.md
> +詳しくは [こちら](server/rules#Modについて) のページをご覧ください。
```suggestion
詳しくは [こちら](/server/rules#modについて) のページをご覧ください。
```

2022-08-14 01:28 UTC, minhero-exp commented on support/faq.md
> +当該権限を付与されたプレイヤーはWorldEditの選択ツール(木の斧)で範囲指定したのち、`/chuocity claim [保護の名前]`とコマンド入力することで範囲保護を作成することができ、この範囲内で自由にWorldEditをご利用になれます。
```suggestion
```

2022-08-16 13:35 UTC, Hiratake commented
なんかコンフリクトしてたから直したらlintエラーになったわね

2022-08-16 13:36 UTC, book000 commented
更新日時の更新がupstream/mainで通ったせいっぽい。ざくろさんめんどくさがるだろうしこちらで変更したわね

2022-08-16 13:39 UTC, Hiratake commented
えきぱ氏が指摘してる箇所は全部変更済みっぽいので、マージしても良いですかね？
承認してもらったほうが良いなら、もっかいレビューのリクエスト投げるとかしたほうがわかりやすいかもわね。

2022-08-17 12:46 UTC, minhero-exp approved these changes

2022-08-17 12:49 UTC, merged