Discordサーバのルールページについて、「jao Minecraft Server独自のDiscordルールである」旨を追記
jaoafa/jaoweb-docs pull request #175
Opened 2022-08-09 08:29 UTC by Omuretsu

表題のとおりです。
詳しくは変更箇所を確認してください。

close #173

2022-08-09 08:31 UTC, Omuretsu commented
ページタイトルは今の所変更していないのですが、こちらも「jao鯖独自のルール」と明確にしたほうがよいと思います。
というのも、「Discord ルール」と検索した際、検索結果の1ページ目にサジェストされるためです。
かといって、変更案が思いつかないのですが...

2022-08-09 08:49 UTC, book000 requested changes

2022-08-09 08:49 UTC, book000 commented on server/rules/discord.md
> +なお、**このDiscordサーバルールはDiscord社が定めたものではありません。**
```suggestion
なお、**このDiscordサーバルールはDiscord Inc.が定めたものではありません。**  
```

2022-08-09 08:49 UTC, book000 commented on server/rules/discord.md
> +このページでの「運営」とは、 jao Minecraft Server での運営スタッフのことを指します。
段落変える場合は末尾スペース2ついらないはず…？

```suggestion
このページでの「運営」とは、 jao Minecraft Server での運営スタッフのことを指します。
```

2022-08-09 08:56 UTC, book000 commented
> ページタイトル

正直、どうでもいいかなあと思ってはいるんですけどね…

まず第一に、シークレットモードで `Discord ルール` と検索したところで出てくるのは7件目ですし、他サーバのルールページも多くサジェストされています。

<details>
<summary>スクショ</summary>

![image](https://user-images.githubusercontent.com/8929706/183607644-d032d330-17c0-4988-a2ea-8144bf5b648a.png)
</details>

うちの場合、SEO用のdescriptionをはっきり書いているので `jao Minecraft Serverの公式Discordサーバ「jMS Gamers Club」のルール・方針を記載します。` という文言も検索ページ上に出てきますし、間違ってこれを見て「Discord全体としてこんなルールがあるんだ」とはならないでしょう。
わざわざタイトルを冗長にしても正直効果があるようには思えない（現時点で問題視するほどでもない）ので、今回の変更だけで十分だと思います。

2022-08-09 09:19 UTC, minhero-exp commented
今回の変更の通り、ページ冒頭への追記のみで良いと思います。
「Discordサーバルール」のページタイトルを変更 (jao鯖のものであると明記) するのであれば、他の「サーバルール」などのページタイトルも変更しなくてはならなくなる気がしますし、サイト内でのページタイトルの統一感も考え、ページタイトルはこのままでいいと思います。

2022-08-09 17:33 UTC, book000 approved these changes

2022-08-10 05:53 UTC, Omuretsu commented
では、ページタイトルについてはこのままにしようと思います。

2022-08-10 06:52 UTC, minhero-exp approved these changes

2022-08-14 01:19 UTC, Hiratake approved these changes

2022-08-14 03:27 UTC, yuuahp approved these changes

2022-08-14 03:49 UTC, merged