ページ「サーバ仕様」内コマンド一覧を更新
jaoafa/jaoweb-docs pull request #177
Opened 2022-08-11 11:57 UTC by minhero-exp

表題の通り。`/debstick` の件もここで修正しています。

2022-08-11 12:00 UTC, Omuretsu commented
細かいところですが、6行目"updatedAt: 2022-05-19"の部分の更新をお願いします。
（今回編集されていない部分だったので、こちらからのsuggestができませんでした。）

2022-08-11 12:04 UTC, Omuretsu requested changes
細かいところですが、6行目"updatedAt: 2022-05-19"の部分の更新をお願いします。
（今回編集されていない部分だったので、こちらからのsuggestができませんでした。）

2022-08-11 12:35 UTC, Omuretsu approved these changes

2022-08-11 13:17 UTC, book000 approved these changes

2022-08-14 01:20 UTC, Hiratake approved these changes

2022-08-14 01:21 UTC, merged