「鉄道方針」「自治体方針」の改定
jaoafa/jaoweb-docs pull request #181
Opened 2022-08-13 09:07 UTC by Omuretsu

**【鉄道方針の改定】**
・「方針を制定している理由」を記載しました。
・「鉄道路線および付帯施設において、運営が管理していると混合するような名称の利用を禁止する」旨を記載しました。

**【自治体方針の改定】**
・「自治体名称において、運営が管理していると混合するような名称の利用を禁止する」旨を記載しました。

2022-08-13 09:08 UTC, Omuretsu commented
close #179

2022-08-13 09:10 UTC, Omuretsu commented
本来であれば、Discord内での議論および審議を経てPullRequestを承認するのが適切ですが、議論が進まないため一旦こちらで変更を提案します。
ある程度このPullRequest内で議論がまとまり次第、Discord内で審議を取り、実装・告知を行います。

@Hiratake @book000 
したがって、全員のApproveが取れても、Mergeせぬようお願いいたします。

2022-08-13 09:15 UTC, yuuahp approved these changes

2022-08-13 10:03 UTC, book000 commented
- プルリクがdraftの場合はこちらでマージボタン押せないのでだいじょうぶです
- `close #xxx` は一番最初のメッセージに入れないと関連付けされないので、もし書き忘れた場合は一番最初のメッセージをeditすることをお勧めします

2022-08-13 10:08 UTC, book000 requested changes

2022-08-13 10:08 UTC, book000 commented on server/guidelines/cities.md
> +- 「自治体名称」には、運営が管理している自治体`中央市`と混同するような名称は使用できません。
これは中央市に限らす、他の時死体と誤認/混合するような名称も微妙なのでなんとも

2022-08-13 10:08 UTC, book000 commented on server/guidelines/railways.md
> +jao Minecraft Server の運営チームや一部常連プレイヤーは、「鉄道敷設」や「鉄道管理」そのものに**あまり良い印象を持ってません**。これは過去に、鉄道敷設に関するトラブルがあったためです。
```suggestion
jao Minecraft Server の運営チームや一部常連プレイヤーは、「鉄道敷設」や「鉄道管理」そのものに**あまり良い印象を持っていません**。これは過去に、鉄道敷設に関するトラブルがあったためです。  
```

2022-08-13 18:17 UTC, Omuretsu commented on server/guidelines/cities.md
> +- 「自治体名称」には、運営が管理している自治体`中央市`と混同するような名称は使用できません。
```suggestion
- 「自治体名称」には、運営が管理している自治体`中央市`と混同するような名称は使用できません。  
- 「自治体名称」には、他ユーザが既に取得・管理している自治体と混同するような名称は使用できません。（ただし、当該自治体を管理するユーザから、類似した名称の使用が明確に許諾されている場合には、その限りではありません。）
```

変更するとしたら、以上のような形になるでしょうか？

2022-08-13 20:55 UTC, book000 commented on server/guidelines/cities.md
> +- 「自治体名称」には、運営が管理している自治体`中央市`と混同するような名称は使用できません。
リストの場合末尾スペース二つはいらないです。
文章内容的にはよいとおもいます

2022-08-13 21:08 UTC, Omuretsu commented on server/guidelines/cities.md
> +- 「自治体名称」には、運営が管理している自治体`中央市`と混同するような名称は使用できません。
> リストの場合末尾スペース二つはいらないです。

失礼しました。修正しました。
では、このままCommitとResolve Conversationをします。

2022-08-15 18:32 UTC, kohonayoshi requested changes

2022-08-15 18:34 UTC, book000 approved these changes

2022-08-15 18:54 UTC, Omuretsu commented on server/guidelines/railways.md
>  - 鉄道・道路を作成できるのはVerified権限からです。
```suggestion
- Verified以上の権限を持つユーザが、鉄道・道路を作成できます。
```

たしかに、`Verified権限以上`とした方が明確ですね。
ただし、` 鉄道・道路を作成できるのはVerified権限以上です。`としてしまうと文章が若干おかしくなるので、上記のSuggestionでいかがでしょうか？

2022-08-15 18:55 UTC, Omuretsu commented on server/guidelines/railways.md
>  - 鉄道・道路を作成できるのはVerified権限からです。
もしこの提案でOKなのであれば、`Commit suggestion`を押して、この会話をResolveしてください。

2022-08-16 03:58 UTC, Omuretsu commented on server/guidelines/railways.md
> +- すべての作業(新設・延伸・撤去など)において、周辺の自治体への明確な相談・合意が必要です。
```suggestion
- すべての作業(新設・延伸・経路変更・撤去など)において、周辺の自治体への明確な相談・合意が必要です。  
```

> 延伸は新設に含まれると思います。

Webサイトおよびこの方針が一般ユーザに向けたものであることを考えると、それぞれ独立して記述したほうが適切だと思われます。

2022-08-16 08:28 UTC, Omuretsu commented on server/guidelines/railways.md
>  - 鉄道・道路を敷設できるのは、中央市を除いた自治体の範囲内のみです。
```suggestion
- 鉄道・道路を敷設できるのは、中央市を除いた自治体の範囲内のみです。自治体として取得されていない土地では、鉄道・道路の敷設はできません。
```

2022-08-16 08:30 UTC, Omuretsu commented on server/guidelines/cities.md
>  - 「自治体名称」には、現存する(または現存した)国名・地名・社名・人名・商標名は原則的に使用できません。
> 自治体内の地名まで縛ることは不可能でしょう。 (https://github.com/jaoafa/jaoweb-docs/pull/181#discussion_r945135899)

> 自治体内の地名に関しては、他自治体管理者と相談や合意をした場合を除き、他自治体に類似する命名を禁止にしたほうがいいかも知れません。 (https://github.com/jaoafa/jaoweb-docs/pull/181#discussion_r945136222)

→どちらの方針を採用すればよいでしょうか...?

2022-08-20 13:24 UTC, Omuretsu commented
強豪を解消してしまいました...

2022-08-23 15:23 UTC, kohonayoshi commented on server/guidelines/cities.md
>  - 「自治体名称」には、現存する(または現存した)国名・地名・社名・人名・商標名は原則的に使用できません。
> 自治体内の地名に関しては、他自治体管理者と相談や合意をした場合を除き、他自治体に類似する命名を禁止にしたほうがいいかも知れません。
で良いかと思います。

2022-08-23 15:25 UTC, kohonayoshi commented on server/guidelines/railways.md
> +- すべての作業(新設・延伸・撤去など)において、周辺の自治体への明確な相談・合意が必要です。
すみませんが、いい文章思いつかないので、他の方が思いつかないのであればこのままか削除するかでお願いします。

2022-08-23 16:03 UTC, Omuretsu commented on server/guidelines/cities.md
> +- 「自治体名称」には、運営が管理している自治体`中央市`と混同するような名称は使用できません。
@kohonayoshi 
https://github.com/jaoafa/jaoweb-docs/pull/181/commits/edf58af5842dc71e8274b1c8a3005d13c80f9b33 で修正しました。これで内容が解決しうる場合は、会話の終了をお願いします。

2022-08-23 16:08 UTC, kohonayoshi approved these changes

2022-08-26 12:30 UTC, minhero-exp approved these changes

2022-08-28 12:16 UTC, lncongruence requested changes

2022-08-28 12:16 UTC, lncongruence commented on server/guidelines/railways.md
> +- サーバ内の各所に、独断で鉄道を敷設する
```suggestion
- 鉄道敷設を独断で行い、サーバ内のインフラを利己的に整備することによる、他自治体の**主権侵害**および実質的な**支配**
- 上記行為のエスカレートによるサーバ内での鉄道をめぐる覇権争いの勃発による、**コミュニティの治安悪化**
```
独断で鉄道を敷設する行為自体は悪質な行為と広く認識されていないと思われます。書くべきは当サーバに独断で鉄道を敷設する行為が嫌われる理由です。

2022-08-28 12:21 UTC, lncongruence approved these changes

2022-08-28 13:06 UTC, Hiratake approved these changes

2022-08-28 13:06 UTC, merged