Readme.mdの情報を更新
jaoafa/jaoweb-docs pull request #189
Opened 2022-08-26 12:58 UTC by Omuretsu

【README】
・AdminWikiのプライベートリポジトリ化に伴う情報の更新
・レビュワーについての記載を更新
など

【LimitedVerified解説ページ】
・トップ画像の追加

2022-08-26 13:06 UTC, book000 requested changes

2022-08-26 13:06 UTC, book000 commented on README.md
> +[解説記事はこちら](https://adminwiki.jaoafa.com/website)
そもそもAdminWikiから当該ページをすべて削除したので、この行自体不要です。

2022-08-26 13:08 UTC, book000 commented
> support/faq.md: 更新日時が変更されていません (Wed Aug 17 2022 00:00:00 GMT+0000 (Coordinated Universal Time))

2022-08-26 13:12 UTC, Omuretsu commented on README.md
> +[解説記事はこちら](https://adminwiki.jaoafa.com/website)
https://github.com/jaoafa/jaoweb-docs/pull/189/commits/0d6f37d942908f6c94302129ef8f6018013c9796 で修正しました。

2022-08-26 13:18 UTC, book000 commented on README.md
> +[解説記事はこちら](https://adminwiki.jaoafa.com/website)
Markdownファイルへのリンクまで消さなくてもよかったかもしれんけど…まあいっか！w

2022-08-26 13:19 UTC, book000 commented on README.md
> +[解説記事はこちら](https://adminwiki.jaoafa.com/website)
と思ったら再追加しとるやん

2022-08-26 13:20 UTC, book000 approved these changes

2022-08-26 14:11 UTC, Omuretsu commented on README.md
> +[解説記事はこちら](https://adminwiki.jaoafa.com/website)
一度消した後に、やっぱり編集サンプルは必要だと思ったので再追加しました。

2022-08-26 17:28 UTC, Omuretsu commented on README.md
> +## 編集方法の仕方
```suggestion
## 編集の仕方
```

2022-08-27 00:56 UTC, Hiratake approved these changes

2022-08-27 00:57 UTC, merged