「はじめての方へ」ページの記述の整理
jaoafa/jaoweb-docs pull request #198
Opened 2023-05-04 22:45 UTC by Omuretsu

「建築について」見出し内、自治体取得に関わる記述が二重になっていたので修正。および記述内容の整理。

2023-05-05 07:54 UTC, book000 requested changes

2023-05-05 07:54 UTC, book000 commented on server/beginners.md
> +取得には、「[jao Minecraft Server Members Club (clubjaoafa)](https://club.jaoafa.com)」というWebサイト上での申請が必要です。
```suggestion
取得には、「[jao Minecraft Server Members Club (clubjaoafa)](https://club.jaoafa.com)」というWebサイト上での申請が必要です。
```

ここの改行スペース2ついらない…よね？

2023-05-05 10:55 UTC, book000 approved these changes

2023-06-07 02:38 UTC, Hiratake approved these changes

2023-06-07 02:38 UTC, merged