docs: リンクテキストの修正
jaoafa/jaoweb-docs pull request #217
Opened 2023-07-04 10:42 UTC by Omuretsu

・リンクテキストの修正
参考） https://twitter.com/cloud10designs/status/1675777447680413696?s=61&t=g0LvPJw3ytjKLpVAMBcx0g

・FAQページ内の重複項目を削除

2023-07-04 10:44 UTC, Omuretsu commented
勢いで修正したので、変なところとか「ここは直さなくていいんじゃないか」っていうところがあったら指摘お願いします🙏

2023-07-04 12:24 UTC, Omuretsu commented
ブログ記事については、今回修正してないです。

2023-07-08 12:09 UTC, book000 requested changes

2023-07-08 12:09 UTC, book000 commented on server/guidelines/cities.md
> +- [jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちらのブログ記事](/support/faq/#q-jms-minecraft-server-members-club-のパスワードを忘れてしまった)をご確認ください。
```suggestion
- [jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[よくあるご質問](/support/faq/#q-jms-minecraft-server-members-club-のパスワードを忘れてしまった)をご確認ください。
```

よくあるご質問は固定ページであり、ブログ記事ではないので不適切かと…。

2023-07-08 12:09 UTC, book000 commented on server/policies/bans.md
> +公式Discordサーバにおける運営・処罰方針については、[Discordサーバルール](server/rules/discord)をご確認ください。
```suggestion
公式Discordサーバにおける運営・処罰方針については、[Discordサーバルール](/server/rules/discord)をご確認ください。
```

これスラッシュ抜けていると `/server/policies/server/rules/discord` に遷移してしまうのでダメな気がします。（そうです…よね？）

2023-07-08 12:09 UTC, book000 commented on server/specifications.md
> +当サーバのDynmapは[こちらのリンク](https://map.jaoafa.com/)(`map.jaoafa.com`)からご覧いただけます。
この変更は、参考元的に微妙なのではと思います。
「リンク先のページタイトル」・「リンク先のページにある情報を説明している」・「リンク先のページで達成できることを説明している」ことが期待されるのであれば、「こちら」から「こちらのリンク」に変えたところで何らリンクテキストとしてユーザーにもたらされる情報は変わっていないのではと思います。

修正を施すのであれば、以下でしょうか。ページタイトルにするだけで十分だと思います。

```suggestion
当サーバのDynmapは[jao Minecraft Server Map](https://map.jaoafa.com/)(`map.jaoafa.com`)からご覧いただけます。
```

そもそも、突然セクションタイトルとして `Dynmapについて` と出てきても知らない人からすれば脳内？な状態なので、「サーバ内マップについて」とかであるべきだとも思いますよねえ。ここで直すべきかどうかはともかくですが…。

2023-07-08 15:52 UTC, Omuretsu commented on server/guidelines/cities.md
> +- [jMS Minecraft Server Members Club](https://club.jaoafa.com/)のログインパスワードを忘れてしまった場合は、[こちらのブログ記事](/support/faq/#q-jms-minecraft-server-members-club-のパスワードを忘れてしまった)をご確認ください。
たしかに...

2023-07-08 15:53 UTC, Omuretsu commented on server/specifications.md
> +当サーバのDynmapは[こちらのリンク](https://map.jaoafa.com/)(`map.jaoafa.com`)からご覧いただけます。
Dynmapについての説明を少し加えるべきだと思いました。考えます。

2023-07-08 15:54 UTC, book000 commented on server/specifications.md
> +当サーバのDynmapは[こちらのリンク](https://map.jaoafa.com/)(`map.jaoafa.com`)からご覧いただけます。
というか、とっつきやすくないセクションタイトルだと流し見する可能性もあるし、目次から辿りづらいよなあと思ったり

2023-07-08 23:28 UTC, Omuretsu commented on server/specifications.md
> +当サーバのDynmapは[こちらのリンク](https://map.jaoafa.com/)(`map.jaoafa.com`)からご覧いただけます。
https://github.com/jaoafa/jaoweb-docs/pull/217/commits/f3a393590dbba95ef9c2a93f52b3d02007252b24 で対応しました。

・見出し文を変更
・見出し文からつながるように、Dynmapの説明を変更
・リンクテキストを修正

この記述で問題なければ、Resolveをお願いします。

2023-07-08 23:31 UTC, Omuretsu commented on server/policies/bans.md
> +公式Discordサーバにおける運営・処罰方針については、[Discordサーバルール](server/rules/discord)をご確認ください。
https://github.com/jaoafa/jaoweb-docs/pull/217/commits/0b3a29861164c4441b9b1c64ff4b113e2dc0df1e で対応しました。
`Commit suggestion`をすればよかったところを何故かVSCodeから修正してしまったので、問題なければResolveをお願いします。

2023-07-09 04:33 UTC, book000 approved these changes

2023-07-29 08:50 UTC, Hiratake approved these changes

2023-07-29 08:50 UTC, merged