docs: ブログ記事の追加
jaoafa/jaoweb-docs pull request #218
Opened 2023-07-29 10:02 UTC by Omuretsu

2023-07-29 10:14 UTC, Omuretsu commented
鯖閉鎖イベントについては書いてないです。

2023-07-29 10:24 UTC, book000 requested changes
途中っぽいですが、とりあえず。

2023-07-29 10:24 UTC, book000 commented on blog/theend.md
> +- `2023年08月02日 22時00分`を以てサーバを停止し、jao Minecraft Server のサービス提供を終了します。
重要事項なので、太字でいきましょう。日時はコードにする必要ないと思います。

```suggestion
- **2023年08月02日 22時00分を以てサーバを停止し、jao Minecraft Server のサービス提供を終了します。**
```

2023-07-29 10:24 UTC, book000 commented on blog/theend.md
> +
```suggestion

いずれも、今後の対応について詳しい事柄はDiscordにて継続的に告知いたします。

```

ここでなくてもいいけど、こういうことは書いといてもいいかも。

2023-07-29 10:24 UTC, book000 commented on blog/theend.md
> +7 年以上にわたって運営を続けているなかで、就職や転職など、運営チームに所属する各々の私生活が大きく変化しました。そのため、サービス運営のためのまとまった時間を取ることが難しくなっています。
```suggestion
7 年以上にわたって運営を続けているなかで、就職や転職など、運営チームに所属する各々の私生活が大きく変化しました。そのため、サービス運営のためにまとまった時間を取ることが難しくなっています。  
```

細かいところですみませんが、こっちの方がいいかと

2023-07-29 10:24 UTC, book000 commented on blog/theend.md
> +サービスを提供するためには、サーバが必要となります。jao Minecraft Server 　は、管理人の[Zakuro]()がいわゆる自宅サーバを用意することによって、運営されています。この自宅サーバを諸事情により、2023 年 08 月上旬から 1 ヶ月以上にわたり、停止することとなりました。
```suggestion
サービスを提供するためには、サーバが必要となります。jao Minecraft Server は、管理人の[Zakuro]()が自宅サーバを用意することによって、運営されています。この自宅サーバを諸事情により、2023 年 08 月上旬から 1 ヶ月以上にわたり、停止することとなりました。  
```

全角スペースが入ってます。「自宅サーバ」は一般用語だと思うので、「いわゆる」は不要です。

2023-07-29 10:24 UTC, book000 commented on blog/theend.md
> +## サービスの提供を終了することを、決定した過程について
これ、いらんでしょ。「運営チームで綿密に話し合いを行い、サービスの終了を決定しました。」の一文で十分だと思います。
詳しいところを知っても、仕方ないので。

2023-07-29 10:24 UTC, book000 commented on blog/theend.md
> +`2016年04月09日`の運営開始以来、
```suggestion
2016年04月09日の運営開始以来、
```
こちらも、日時についてはコードにする必要ないと思います。普通の文中の日本語ですし。

2023-07-29 12:34 UTC, Omuretsu commented on blog/theend.md
> +## サービスの提供を終了することを、決定した過程について
https://github.com/jaoafa/jaoweb-docs/pull/218/commits/3f032f9dcee51a5b54d5dda123aa2d8714887a39 で削除しました。

2023-07-29 12:36 UTC, Omuretsu commented on blog/theend.md
> +
https://github.com/jaoafa/jaoweb-docs/pull/218/commits/b63e4c149e45b9842f37c63451d1946e4d5d1b7c で修正しました。

2023-07-29 13:43 UTC, book000 requested changes

2023-07-29 13:43 UTC, book000 commented on blog/theend.md
> +ワールドデータを、準備が整い次第公式 Discord サーバ内にて公開・配布します。
```suggestion
ワールドデータを、準備が整い次第公式 Discord サーバ内にて公開・配布します。  
```

改行漏れっぽく見えます

2023-07-29 13:43 UTC, book000 commented on blog/theend.md
> +サービスの終了に伴い、公式 Web サイトの[お問合せフォーム](/support/inquiry)も閉鎖いたします。
```suggestion
サービスの終了に伴い、公式 Web サイトの[お問い合わせフォーム](/support/inquiry)も閉鎖いたします。  
```

送り仮名抜けかな？

2023-07-29 13:43 UTC, book000 commented on blog/theend.md
> +jao Minecraft Server は開設以来、多くの利用者様にログイン頂いていました。しかし近年は、「週末や休日でも、1 日を通してログインする人が 1 人もいない」という状況でした。
```suggestion
jao Minecraft Server は開設以来、多くの利用者の皆様にログイン頂いていました。しかし近年は、「週末や休日でも、1 日を通してログインする人が 1 人もいない」という状況でした。  
```

「利用者の皆様」と「利用者様」の表記揺れが気になります。特定の個人を指さないのであれば、「利用者の皆様」でよさそうです。
漢字2文字の「皆様」と、ひらがなを含む「皆さま」のどっちが良いかはお任せします。（個人的には、ひらがなが入ってた方が柔らかくて好きです）

2023-07-29 13:43 UTC, book000 commented on blog/theend.md
> +2016 年 04 月 09 日の運営開始以来、多くの利用者様にサービスをご利用いただきましたこと、運営チーム一同心より御礼申し上げます。今後も Discord サーバなどを通じて、多くの人にとって楽しいコミュニティを維持・発展できるように努めてまいります。よろしくお願いいたします。
```suggestion
2016 年 04 月 09 日の運営開始以来、多くの利用者の皆様にサービスをご利用いただきましたこと、運営チーム一同心より御礼申し上げます。

今後も Discord サーバなどを通じて、多くの人にとって楽しいコミュニティを維持・発展できるように努めてまいります。よろしくお願いいたします。
```

表記揺れ修正入れてます。
文が長く感じるので、今までとこれからで段落を切った方が良さそう。
ご協力よろしくお願いいたしますとかいりますかね？

2023-07-29 13:54 UTC, Omuretsu commented on blog/theend.md
> +jao Minecraft Server は開設以来、多くの利用者様にログイン頂いていました。しかし近年は、「週末や休日でも、1 日を通してログインする人が 1 人もいない」という状況でした。
なんかもともとの文章が若干違和感ありますね。以下でどうでしょうか？
```suggestion
jao Minecraft Server は開設以来、多くの利用者の皆様にログイン頂きました。しかし近年は、「週末や休日でも、1 日を通してログインする人が 1 人もいない」という状況でした。 

皆様か皆さまについては、後ほど確認します。 
```

2023-07-29 13:54 UTC, book000 commented on blog/theend.md
> +jao Minecraft Server は開設以来、多くの利用者様にログイン頂いていました。しかし近年は、「週末や休日でも、1 日を通してログインする人が 1 人もいない」という状況でした。
👌

2023-07-29 13:55 UTC, Omuretsu commented on blog/theend.md
> +2016 年 04 月 09 日の運営開始以来、多くの利用者様にサービスをご利用いただきましたこと、運営チーム一同心より御礼申し上げます。今後も Discord サーバなどを通じて、多くの人にとって楽しいコミュニティを維持・発展できるように努めてまいります。よろしくお願いいたします。
ご協力は、いらない気がします。どうでしょうか？

2023-07-29 13:56 UTC, Omuretsu commented on blog/theend.md
> +jao Minecraft Server は開設以来、多くの利用者様にログイン頂いていました。しかし近年は、「週末や休日でも、1 日を通してログインする人が 1 人もいない」という状況でした。
ではこれで`Commit Suggestion`します。

2023-07-29 13:56 UTC, book000 commented on blog/theend.md
> +2016 年 04 月 09 日の運営開始以来、多くの利用者様にサービスをご利用いただきましたこと、運営チーム一同心より御礼申し上げます。今後も Discord サーバなどを通じて、多くの人にとって楽しいコミュニティを維持・発展できるように努めてまいります。よろしくお願いいたします。
おっけーです👌じゃあ良ければこれでー。

2023-07-29 14:17 UTC, Omuretsu commented
@book000 https://github.com/jaoafa/jaoweb-docs/pull/218/commits/ffcd41d6ad6aa719b7cbf30b5643d01e84223d84 で`皆様`を`皆さま`に置き換えました。

2023-07-29 14:27 UTC, book000 requested changes
繰り返しでごめんなさい。ラストの記事になるので、色々気になってしまって…

2023-07-29 14:27 UTC, book000 commented on blog/theend.md
> +サービスを提供するためには、サーバが必要となります。jao Minecraft Server は、管理人の Zakuro が自宅サーバを用意することによって、運営されています。この自宅サーバを諸事情により、2023 年 08 月上旬から 1 ヶ月以上にわたり、停止することとなりました。
```suggestion
サービスを提供するためには、サーバが必要となります。jao Minecraft Server では、管理人の Zakuro が自宅サーバを用意することによって運営されています。  
この自宅サーバを諸事情により、2023 年 08 月上旬から 1 ヶ月以上にわたり、停止することとなりました。

```

繰り返しrequest changesでごめんなさい。
読点の位置がおかしそうなのと、事実とそれによる判断で段落分けをしないと見づらそうかなと思ったりしました。

2023-07-29 14:27 UTC, book000 commented on blog/theend.md
> +以前より上述の課題を運営チーム内で話し合う中で、今回のサーバ停止がサービス提供を終了するいい機会だと捉えました。
```suggestion
以前より上述の課題を運営チーム内で話し合う中で、今回のサーバ停止がサービス提供を終了するよい機会だと捉えました。
```

「いい」は口語（喋り言葉）だった筈です。良い or 平仮名のよいを選ぶべきかなと思います。

2023-07-29 14:27 UTC, book000 commented on blog/theend.md
> +これに対して、「誰も参加しないサーバを、これからも維持管理することは難しい」という意見が、運営チーム内であがっていました。
```suggestion

これに対して、「誰も参加しないサーバを、これからも維持管理することは難しい」という意見が、運営チーム内であがっていました。
```

事実と事実を元にした判断で段落分けをすると見やすそうだな感があります

2023-07-29 14:27 UTC, book000 commented on blog/theend.md
> +利用者の皆さまに安心してサービスをご利用頂くための、サーバやプラグインなどのメンテナンスも疎かになることが考えらます。そのため、これ以上サービスを運営することは困難だと判断しました。
```suggestion

利用者の皆さまに安心してサービスをご利用頂くための、サーバやプラグインなどのメンテナンスも疎かになることが考えらます。そのため、これ以上サービスを運営することは困難だと判断しました。
```

事実と事実を元にした判断で段落分けをすると見やすそうだな感があります

2023-07-29 14:30 UTC, yuuahp commented on blog/theend.md
> +- 付随する[Web サイト](/)や[ブログ](/blog)についても、閉鎖します。
```suggestion
- 付随する [Web サイト](/)や[ブログ](/blog)についても、閉鎖します。
```
英単語の前後に半角スペースを入れてそうだったのでここもかなと

2023-07-29 14:30 UTC, yuuahp commented on blog/theend.md
> +- 公式 Discord サーバについては、権限付与方法やチャンネル設定などを変更した上で、今後も運営チームが運営を継続します。
「コミュニティーとしてこれからも運営していきます」的なことはこっちにも含めたほうが良いと思います

2023-07-29 14:30 UTC, yuuahp commented on blog/theend.md
> +jao Minecraft Server では、これまで 7 年以上にわたって提供してきました、Minecraft サーバのサービス提供を終了することとなりました。突然のお知らせとなり、利用者の皆様にはご迷惑をおかけいたしますが、ご承知おきください。
```suggestion
jao Minecraft Server では、これまで 7 年以上にわたって提供してきました Minecraft サーバのサービス提供を終了することとなりました。突然のお知らせとなり、利用者の皆様にはご迷惑をおかけいたしますが、ご承知おきください。
```

「動詞してきました、名詞を」に違和感がある気がします
「動詞してきました / 名詞」ではなく「動詞してきました名詞」として繋がっているんじゃないかなと
日本語強い人よろしくお願いします

2023-07-29 14:30 UTC, yuuahp commented on blog/theend.md
> +サービスの終了に関するお問い合わせ、今後のコミュニティ運営に関わるお問い合わせなどは、公式 Discord サーバ内`#support`までお送りください。
```suggestion
サービスの終了に関するお問い合わせ、今後のコミュニティ運営に関わるお問い合わせなどは、公式 Discord サーバ内 `#support` までお送りください。
```
こちらも前後スペースです

2023-07-29 14:32 UTC, book000 commented on blog/theend.md
> +- 付随する[Web サイト](/)や[ブログ](/blog)についても、閉鎖します。
これやるなら、リンクの前後に全部スペース入れてもいいかもしれません

2023-07-29 15:59 UTC, Omuretsu commented
> 繰り返しでごめんなさい。ラストの記事になるので、色々気になってしまって…

まあそれはとてもそう。

2023-07-29 16:06 UTC, Omuretsu commented on blog/theend.md
> +- 公式 Discord サーバについては、権限付与方法やチャンネル設定などを変更した上で、今後も運営チームが運営を継続します。
https://github.com/jaoafa/jaoweb-docs/pull/218/commits/a72339d91e5683dbcb7f451be82bc2a393290b6c で修正しました。この変更で良ければ、`Resolve`をおねがいします。

2023-07-29 16:06 UTC, Omuretsu commented on blog/theend.md
> +- 公式 Discord サーバについては、権限付与方法やチャンネル設定などを変更した上で、今後も運営チームが運営を継続します。
@yuuahp

2023-07-29 16:09 UTC, book000 approved these changes
内容についてオッケーです。authorについてはざくろあたりに確認の上、変更した上でマージしてください。

2023-07-29 16:22 UTC, Omuretsu commented on blog/theend.md
> +jao Minecraft Server では、これまで 7 年以上にわたって提供してきました、Minecraft サーバのサービス提供を終了することとなりました。突然のお知らせとなり、利用者の皆様にはご迷惑をおかけいたしますが、ご承知おきください。
@yuuahp 
とりあえず https://github.com/jaoafa/jaoweb-docs/pull/218/commits/6631ff353f35a94d49a89d247f841dae3258765e https://github.com/jaoafa/jaoweb-docs/pull/218/commits/79c1ed3a3cf31b956f5068dddf8b29ce120ede1f で修正しました。
そもそも文章が冗長になっていたので、いくつかに分割しています。

ここの主語って、`jao Minecraft Server`なのか、`jao Minecraft Server 運営チーム`なのか、どっちがいいんですかね...。

2023-07-29 16:24 UTC, Omuretsu commented on blog/theend.md
> +- 付随する[Web サイト](/)や[ブログ](/blog)についても、閉鎖します。
@yuuahp @book000 https://github.com/jaoafa/jaoweb-docs/pull/218/commits/f7972489704609d87ca6ffabccd1ac4a365819c6 で修正しました。

@yuuahp 問題なければ`Resolve`をおねがいします。

2023-07-29 16:27 UTC, Omuretsu commented on blog/theend.md
> +- **2023 年 08 月 02 日 22 時 00 分を以てサーバを停止し、jao Minecraft Server のサービス提供を終了します。**
Textlintのアレだと思うけど、空白ありありでちょっと気持ち悪いな....。
ここに限った話じゃないけど。

2023-07-29 16:28 UTC, Omuretsu commented
@book000 
すみません。修正箇所が多いのでレビューを指し直しました。

2023-07-29 16:43 UTC, book000 requested changes

2023-07-29 16:43 UTC, book000 commented on blog/theend.md
> +この記事では、サービス提供の終了に至った経緯や、今後の対応についてご説明いたします。
イントロ部分を置き換えます。

```suggestion
この度、jao Minecraft Server では 2023 年 08 月 02 日 22 時 00 分をもって、Minecraft サーバのサービス提供を終了させていただくこととなりました。
利用者のみなさまには、突然のお知らせとなりますことをお詫びいたします。

2016 年 04 月 09 日の運営開始以来 7 年もの間、多くの利用者の皆さまにサービスをご利用いただきましたが、様々な理由からサービスの終了を決定いたしました。
この記事では、サービス提供の終了に至った経緯や、今後の対応についてご説明いたします。
```

2023-07-29 16:48 UTC, book000 requested changes

2023-07-29 16:48 UTC, book000 commented on blog/theend.md
> +author: jaotan
ここはjaotan以外（omelet or zakuro）に変えてください。

2023-07-29 16:49 UTC, Omuretsu commented on blog/theend.md
> +jao Minecraft Server では、これまで 7 年以上にわたって提供してきました、Minecraft サーバのサービス提供を終了することとなりました。突然のお知らせとなり、利用者の皆様にはご迷惑をおかけいたしますが、ご承知おきください。
やっぱりこっちにします。： https://github.com/jaoafa/jaoweb-docs/pull/218#discussion_r1278340999

2023-07-29 16:51 UTC, book000 approved these changes

2023-07-29 17:16 UTC, Omuretsu commented on blog/theend.md
> +- **2023 年 08 月 02 日 22 時 00 分を以てサーバを停止し、jao Minecraft Server のサービス提供を終了します。**
とまちっちいわく、仕方がないらしい。

2023-07-29 23:13 UTC, yuuahp approved these changes

2023-07-29 23:25 UTC, Hiratake approved these changes

2023-07-30 02:15 UTC, lncongruence approved these changes

2023-07-30 02:18 UTC, Omuretsu commented on blog/theend.md
> +author: jaotan
https://github.com/jaoafa/jaoweb-docs/pull/218/commits/e7521d65cdffda3e7b9fe0809daf32da97b25780 で対応しました。

2023-07-30 02:27 UTC, Hiratake requested changes

2023-07-30 02:27 UTC, Hiratake commented on blog/theend.md
> +author: Omelet
`author` には以下の `authors.json` に指定している `slug` の値を指定する必要があります。小文字に変更をおねがいします。
https://github.com/jaoafa/jaoweb/blob/a8354968195b88dc2d33d7c4294d94172ec2e4e0/content/blog/authors.json#L37

```suggestion
author: omelet
```

2023-07-30 02:28 UTC, Hiratake commented on blog/theend.md
> +author: Omelet
上の会話のとこでやればよかった

2023-07-30 02:36 UTC, Hiratake approved these changes

2023-07-30 02:40 UTC, merged