サーバリストサービスでの投票方法と特典のブログ記事の文章を変更
jaoafa/jaoweb-docs pull request #22
Opened 2021-04-03 03:25 UTC by Hiratake

2021-04-03 03:26 UTC, book000 commented on blog/how-to-vote.md
> +jao Minecraft Server では、Minecraftのサーバリストサービスである [Japan Minecraft Servers](https://minecraft.jp) と [monocraft](https://monocraft.net) へ登録しており、それぞれのサイトでの投票を受け付けています。また、投票に対する投票特典も複数ご用意しております。
お前止めたやんか…

2021-04-03 03:32 UTC, book000 requested changes

2021-04-03 03:32 UTC, book000 commented on blog/how-to-vote.md
> +サーバのバージョンが `1.6.2-1.8.0` となっていますが、認証コードは取得できます。
`サーバのバージョンが `1.6.2-1.8.0` となっていますが、どのバージョンでも認証コードは取得できます。 かな。`どのバージョンでも` って書かないと文章としてよくわからん気がするので

2021-04-03 03:32 UTC, book000 commented on blog/how-to-vote.md
> +https://storage.jaoafa.com/2fc14fff72c8b32b9d5566dbbf8e541c.PNG)
これ成立している？

2021-04-03 03:33 UTC, book000 commented
あと、どのコードにというよりかはすべてに対してだけど

> monocraftは Mojang AB および jao Minecraft Server の運営サイトではありません。
> monocraft でアカウント登録をしましょう

> 次に、「Googleアカウント」もしくは「Twitterアカウント」でログインします。
> からMinecraftのアカウントと連携します。

というように、日本語と英語の間を空けるか空けないかまばらなところが若干気になった
別にどっちでもいいけど、執筆者によって合わせてもいいのかなと思ったり

2021-04-06 23:21 UTC, Hiratake commented
> 日本語と英語の間を空けるか空けないかまばらなところ

わたしは単語が2つ以上の場合は前後にスペースいれてる。

2021-04-07 00:15 UTC, book000 commented
naruhodo

2021-04-07 00:16 UTC, book000 approved these changes

2021-04-13 13:50 UTC, minhero-exp commented on blog/how-to-vote.md
> +また、200回以上投票すると、 `/color <color>` コマンドで色を自由に変更することができるようになります。
/colorから/skkcolorに変更したほうがよさそう

2021-04-13 13:53 UTC, minhero-exp commented on blog/how-to-vote.md
> +`<color>` には表にある「色名」をいれてください。
[自由にカラーコードが指定できるようになった](https://github.com/jaoafa/MyMaid4/issues/130)からそのことについても書いたほうがよさそう

2021-04-14 16:32 UTC, book000 commented
一旦マージするので、コマンド名の変更・カラーコード指定についての内容は追記してください。

2021-04-14 16:32 UTC, merged