「WorldEditCUIの導入解説」を1.16.5向けにリライト
jaoafa/jaoweb-docs pull request #29
Opened 2021-04-21 08:58 UTC by minhero-exp

プルリクエストのお試しも兼ねて。
使用方法以外は1.16.5向けに書き直してみました。

2021-04-22 10:47 UTC, minhero-exp commented on blog/worldeditcui-commentary.md
> +すると「ファイル名を指定して実行」と表示されるので「`%appdata%\\.minecraft/mods`」と入力して「OK」をクリックしてください。すると`.minecraft`の`mods`というフォルダーが表示されます。
> .minecraft の前に二つも \ はいらなさそう
なるほど？修正します。
> .minecraft\mods に大量に Mod ファイルを置くと不具合の原因ともなりうる可能性がある
ゲームディレクトリ分けるアレアレは初心者にとって難しそうだから省いてもいいかな～って思ったけど、不具合が起きる可能性があるのはマズそうなので追加しておきます。

2021-04-22 10:53 UTC, minhero-exp commented on blog/worldeditcui-commentary.md
> +- WorldEditCUI Forge Edition 3 1.16.5 3.0.9
> Windows特有のファイルの置き場所やセパレーターとかもあったので...
なるほど。やっぱ必要そうなので追加しておきます。

2021-04-22 13:25 UTC, book000 requested changes

2021-04-22 13:25 UTC, book000 commented on blog/worldeditcui-commentary.md
> +ゲームディレクトリを分けていない場合は`.minecraft\mods`に配置することになりますが、ここにたくさんModを入れると不具合の原因となりますのでおすすめしません。~~ゲームデレクトリの分け方は[こちら](/blog/setting-gamedirectory)で解説しています。~~
「ディレクトリ」です

2021-04-22 13:25 UTC, book000 commented
ここだけ修正されればあとはマージできそうです

2021-04-23 07:36 UTC, minhero-exp commented on blog/worldeditcui-commentary.md
> +ゲームディレクトリを分けていない場合は`.minecraft\mods`に配置することになりますが、ここにたくさんModを入れると不具合の原因となりますのでおすすめしません。~~ゲームデレクトリの分け方は[こちら](/blog/setting-gamedirectory)で解説しています。~~
ｷﾞｬ

2021-04-23 08:44 UTC, merged

2021-04-23 08:45 UTC, book000 commented
やべApprovedするまえにMergeしたけどまあいいか