Blogの5ページ目を全て追加しました
jaoafa/jaoweb-docs pull request #3
Opened 2020-12-21 09:40 UTC by yuuahp

https://jaoafa.com/blog/page/5
確認お願いします🙏

2020-12-21 11:23 UTC, book000 reviewed
新Webサイト仕様は多分`/blog/<CATEGORY>/<ページファイル名>.md`になるはずなので、ファイル名として正当ではない。が、まだこのへんの仕様が未策定でわからないのでRequest changesではなくcomment。

参考: https://github.com/jaoafa/jaoweb/blob/master/content/blog/news/sample.md

2020-12-21 11:25 UTC, book000 commented on blog/tomachi/discord-username.md
> +title:Discordでのユーザ名の変更方法
`title: `

2020-12-21 11:27 UTC, book000 commented
行コメントにしてしまったけど、どのファイルもそうだな…。Markdownの仕様上、`title: タイトル`にならなきゃダメだからこれはよくない

2020-12-21 11:30 UTC, yuuahp commented
`title:{スペース}タイトル`
に修正したほうがいいですか？

2020-12-21 11:32 UTC, book000 commented
> 
> 
> `title:{スペース}タイトル`
> に修正したほうがいいですか？

yes、その通り。だけど、#vcでも言ったようにブログに関しては古いものを取り込むかどうか検討中だからちょっと待って(一部だけマージとかを考えるかも)

2020-12-21 11:33 UTC, yuuahp commented
わかりました

2020-12-21 11:49 UTC, book000 requested changes
全ファイルにおいて、改行を純粋な改行`\n`だけじゃなくて`  \n`にしないとダメかも。
プレビューするとわかるけど、改行抜けちゃうので

2020-12-21 11:50 UTC, yuuahp commented
あっ...
修正します

2020-12-21 12:00 UTC, yuuahp commented
えっこれどうすればいいと思いますか...?
\nをVSCodeで検索しても出てきません...

2020-12-21 12:09 UTC, book000 commented
> 
> 
> えっこれどうすればいいと思いますか...?
> \nをVSCodeで検索しても出てきません...

簡単に対処できないと思う…。正規表現で云々やれるかと思ったけど厳しそう。手動でやるしかないんじゃない？

2020-12-21 12:15 UTC, yuuahp commented
やり直してみたらなんかちょっと不自然な感じで改行されると言いますか...
改行した後に隙間が...

2020-12-21 12:26 UTC, book000 commented
## これはダメ (一番最初のケース)

```markdown
2018/07/16に、jao Minecraft Serverの利用規約を全面改訂し、より分かりやすい規約が公開されました。
この記事では、利用規約の改定に伴う利用者の同意についてや、各所の条名の記載について解説いたします。
```

## これはダメ (今回のケース)

```markdown
2018/07/16に、jao Minecraft Serverの利用規約を全面改訂し、より分かりやすい規約が公開されました。

この記事では、利用規約の改定に伴う利用者の同意についてや、各所の条名の記載について解説いたします。
```

## これは良い

```markdown
2018/07/16に、jao Minecraft Serverの利用規約を全面改訂し、より分かりやすい規約が公開されました。  
この記事では、利用規約の改定に伴う利用者の同意についてや、各所の条名の記載について解説いたします。
```

- 1行目(改行前の行末)に半角スペースを二つ入れる(`  \n`)

というか、VSCodeか何かで書いているならプレビュー機能とか使うといいかと。あと[Markdown Lint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)?

参考: [mignonstyle/markdown-cheatsheet.md](https://gist.github.com/mignonstyle/083c9e1651d7734f84c99b8cf49d57fa#br-%E6%94%B9%E8%A1%8C)

2020-12-21 13:23 UTC, Hiratake commented on blog/tomachi/hello-world.md
> +title:HelloWorld
title: Hello World

2020-12-21 13:23 UTC, Hiratake commented on blog/tomachi/hello-world.md
> +title:HelloWorld
・「title:」の後ろに半角スペースを入れる
・元記事のタイトルが「Hello World」なので「Hello」と「World」の間に半角スペースを入れる

2020-12-21 13:32 UTC, Hiratake requested changes

2020-12-21 13:32 UTC, Hiratake commented on blog/tomachi/hello-world.md
> +---
「title」の下に「author: tomachi」を追加

2020-12-21 13:32 UTC, Hiratake commented on blog/tomachi/hello-world.md
> +---
「createdAt: 2018-03-31」を追加

2020-12-21 13:32 UTC, Hiratake commented on blog/tomachi/hello-world.md
> +---
「updateAt: 2020-12-21」を追加

2020-12-21 13:36 UTC, Hiratake commented on blog/tomachi/hello-world.md
> +
目次は自動挿入されるので不要

2020-12-21 13:41 UTC, Hiratake requested changes

2020-12-21 13:41 UTC, Hiratake commented on blog/tomachi/discord-username.md
> +---
「title」の下に「author: tomachi」を追加

2020-12-21 13:41 UTC, Hiratake commented on blog/tomachi/discord-username.md
> +---
「createdAt: 2018-04-22」を追加

2020-12-21 13:41 UTC, Hiratake commented on blog/tomachi/discord-username.md
> +---
「updatedAt: 2020-12-21」を追加

2020-12-21 13:54 UTC, Hiratake commented on blog/tomachi/discord-username.md
> +# ユーザ名とニックネームについて
H2なので # ではなく ##

2020-12-21 13:55 UTC, Hiratake requested changes

2020-12-21 13:55 UTC, Hiratake commented on blog/tomachi/discord-username.md
> +## ユーザ名
H3なので ## ではなく ###

2020-12-30 13:42 UTC, yuuahp commented
ごめんなさい遅れました....

2021-02-07 00:14 UTC, book000 commented
#8 のプルリクエストに伴い一旦閉じます

2021-02-07 00:14 UTC, closed without merging