コマンド一覧の更新
jaoafa/jaoweb-docs pull request #37
Opened 2021-05-20 12:00 UTC by minhero-exp

「サーバ仕様」内にあるコマンドについての項目を更新しました。

2021-05-20 14:10 UTC, book000 requested changes

2021-05-20 14:10 UTC, book000 commented on server/specifications.md
> +|/itemedit|手に持っているアイテムの情報を編集します|Verified～|
itemeditはまだ実装できていません: https://github.com/jaoafa/MyMaid4/issues/359

2021-05-21 10:32 UTC, minhero-exp commented on server/specifications.md
> +|/itemedit|手に持っているアイテムの情報を編集します|Verified～|
削除しました👋

2021-05-21 11:28 UTC, book000 approved these changes

2021-05-21 11:28 UTC, merged