文章の修正
jaoafa/jaoweb-docs pull request #73
Opened 2021-09-12 23:12 UTC by Omuretsu

**変更箇所がかなり多いです。**

・定義の追加
・二重表現の解消
・一部文章を改行
・その他色々

変更箇所がかなり多いので、ここには上げきれません。
変更ファイルを参照お願いします。
なおまだ気になった箇所が何点かあるので、それは追々修正で。

2021-09-12 23:13 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/73/server/rules/discord)

2021-09-12 23:16 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/73/server/rules/discord)

2021-09-13 09:02 UTC, book000 requested changes
一旦タブレットで確認できる修正項目です
PCでもう一回確認して追加でいくつか追加するかも

2021-09-13 09:21 UTC, book000 commented
PCで確認しました、とりあえず私はこの修正点のみです👍

2021-09-13 09:30 UTC, Omuretsu commented on server/rules/discord.md
> +1. 利用者は公式Discordサーバを利用する場合、必ず以下を理解し、同意しなければなりません。  同意できない場合、公式Discordサーバを利用することはできません。
Sorry.

2021-09-13 09:31 UTC, book000 commented on server/rules/discord.md
> +1. 利用者は公式Discordサーバを利用する場合、必ず以下を理解し、同意しなければなりません。  同意できない場合、公式Discordサーバを利用することはできません。
謝る必要はないよ～～～～～～～～～～～～～～～～～～～～～～～～～～～～誰でも間違えるものは間違えるしレビュー抜けでそのままマージするケースもあるし

2021-09-13 09:31 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/73/server/rules/discord)

2021-09-13 09:39 UTC, Omuretsu commented on server/rules/discord.md
> +1. 上記の「利用条件・遵守事項」をすべて満たさずに、公式Discordサーバへ参加すること
行為行為しててうるさいかなぁと思って外しちゃいました。
付けたほうがよければ付け直します。

2021-09-13 09:41 UTC, book000 commented on server/rules/discord.md
> +1. 上記の「利用条件・遵守事項」をすべて満たさずに、公式Discordサーバへ参加すること
正直どっちがいいのかわからんっちゃわからんですよね、たしかに行為行為してるのうるさいかも…

2021-09-13 09:42 UTC, Omuretsu commented on server/rules/discord.md
> +      または、侵害するおそれのある行為
多分ここは必要なさそう。
直しておきます。

2021-09-13 09:43 UTC, Omuretsu commented
取り急ぎ、やらないといけな課題などがあるのでまた後でで

2021-09-15 03:30 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/73/server/rules/discord)

2021-09-18 03:44 UTC, book000 commented
リマインド:

https://github.com/jaoafa/jaoweb-docs/pull/73#discussion_r707134650 の修正ができてないので、お忘れでしたら…

2021-09-18 08:38 UTC, Omuretsu commented
忘れてました...

2021-09-18 08:39 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/73/server/rules/discord)

2021-09-18 08:56 UTC, book000 approved these changes

2021-09-18 08:57 UTC, merged