server/index.md
jaoafa/jaoweb-docs pull request #75
Opened 2021-09-16 21:34 UTC by book000

- close https://github.com/jaoafa/jaoweb/issues/25

[/server にアクセスすると 403 Forbidden がでる問題](https://jaoafa.com/server/) の暫定修正。

2021-09-16 21:36 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/index.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/75/server/)

2021-09-17 01:57 UTC, Hiratake requested changes

2021-09-17 01:57 UTC, Hiratake commented on server/index.md
> +# サーバ情報
markdownのヘッダがないです。
`# サーバ情報` ではタイトルとパンくずリストの項目が正しく表示されないので、ヘッダに `title` を入れてください。
```
---
title: サーバ情報
createdAt: 2021-09-17
updatedAt: 2021-09-17
---
```

2021-09-17 01:57 UTC, Hiratake commented on server/index.md
> +
見出しが1つもないと空の目次が出てしまうので、仮で `## ページ一覧` 的なのいれといてください。
以下でそのうち対応します。
jaoafa/jaoweb#103

2021-09-18 01:11 UTC, book000 commented on server/index.md
> +# サーバ情報
修正しました…

2021-09-18 01:11 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/index.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/75/server/)

2021-09-18 01:12 UTC, book000 commented on server/index.md
> +
👍

2021-09-18 04:08 UTC, Hiratake commented on server/index.md
> +image: https://storage.jaoafa.com/f54f2539629b70b8f3d78cc694236081.png
デフォの画像は `image` なくてもいいかも。
ガイドラインのページとか入ってないし。

![image](https://user-images.githubusercontent.com/23224932/133871975-0b303a12-d3ff-41d4-ae23-399303bf643a.png)

2021-09-18 04:10 UTC, book000 commented on server/index.md
> +image: https://storage.jaoafa.com/f54f2539629b70b8f3d78cc694236081.png
これ、別ページも随時直した方がいいかも…ヘッドコピペしてきたので…

2021-09-18 04:12 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/index.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/75/server/)

2021-09-18 04:13 UTC, Hiratake approved these changes

2021-09-18 04:13 UTC, merged