Community Regularの項目を追加
jaoafa/jaoweb-docs pull request #77
Opened 2021-09-17 16:31 UTC by Omuretsu

Community Regularの新設に伴い、情報を追加。

2021-09-17 16:32 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/policies/permissions.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/77/server/policies/permissions)

2021-09-18 03:43 UTC, book000 requested changes

2021-09-18 03:43 UTC, book000 commented on server/policies/permissions.md
> +- 最終ログインから3ヶ月が経過し、運営がその理由を把握していない場合。(Verifiedに降格)
```suggestion
- 最終ログインから3ヶ月が経過し、運営がその理由を把握していない場合。(Defaultに降格)
```
最終ログインから3か月が経過した場合、自動的に連携解除がなされるのでDefaultに落ちます

2021-09-21 05:42 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/policies/permissions.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/77/server/policies/permissions)

2021-09-21 05:43 UTC, book000 approved these changes

2021-09-21 05:44 UTC, merged