Discordのアカウント管理について追記
jaoafa/jaoweb-docs pull request #80
Opened 2021-09-18 08:33 UTC by Omuretsu

Discordのアカウント管理について追記を行いました。

2021-09-18 08:35 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/discord-two-factor.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/blog/discord-two-factor)
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/server/rules/discord)

2021-09-18 08:55 UTC, book000 requested changes

2021-09-18 08:55 UTC, book000 commented on blog/discord-two-factor.md
> +インターネットは便利な半面様々な情報がやり取りされており、使い方によってはトラブルに巻き込まれる場合があります。特にDiscordにおいては、特定権限からファイルの送信が可能となっています。もしトラブルがあった場合、貴方だけではなく他利用者にも被害が及ぶ場合があります。
```suggestion
インターネットは便利な反面様々な情報がやり取りされており、使い方によってはトラブルに巻き込まれる場合があります。特にDiscordにおいては、特定権限からファイルの送信が可能となっています。もしトラブルがあった場合、貴方だけではなく他利用者にも被害が及ぶ場合があります。  
```

2021-09-18 08:55 UTC, book000 commented on blog/discord-two-factor.md
> +インターネットは便利な半面様々な情報がやり取りされており、使い方によってはトラブルに巻き込まれる場合があります。特にDiscordにおいては、特定権限からファイルの送信が可能となっています。もしトラブルがあった場合、貴方だけではなく他利用者にも被害が及ぶ場合があります。
> もしトラブルがあった場合、貴方だけではなく他利用者にも被害が及ぶ場合があります。  

違和感…。
「トラブルに遭った場合」？「不正利用などを受けた場合」？

2021-09-18 08:55 UTC, book000 commented on blog/discord-two-factor.md
> +インターネットは便利な半面様々な情報がやり取りされており、使い方によってはトラブルに巻き込まれる場合があります。特にDiscordにおいては、特定権限からファイルの送信が可能となっています。もしトラブルがあった場合、貴方だけではなく他利用者にも被害が及ぶ場合があります。
「貴方」だと無駄に畏まった感が強すぎると思うので、「あなた」にしてしまっても良さげではないでしょーか

2021-09-18 08:55 UTC, book000 commented on server/rules/discord.md
> +- 以上より、（Discordだけに限りませんが）パスワードの使い回しなどはおやめください。またパスワードは信頼できるマネージャーアプリで管理するようにしましょう。
```suggestion
- 以上より、（Discordだけに限りませんが）パスワードの使い回しなどはおやめください。またパスワードは信頼できるマネージャーアプリなどで管理するようにしましょう。
```

マネージャーアプリでの管理が一概に正しいとは言えないので(外部ツールを使うよりメモ帳に書いて金庫に入れたほうが安全かもしれない)、「など」をつけときましょう

2021-09-18 08:55 UTC, book000 commented on server/rules/discord.md
> +   詳細は[ブログ『Discordで二段階認証をする方法』](/blog/discord-two-factor)をご参照ください。
```suggestion
   詳細は[ブログ「Discordで二段階認証をする方法」](/blog/discord-two-factor)をご参照ください。
```
かぎかっこの優先度が違うように見えます
「」→『』では？

2021-09-18 08:55 UTC, book000 commented on server/rules/discord.md
> +- 万が一アカウントが不正利用された可能性がある場合は、運営へお問い合わせ・ご報告ください。
```suggestion
- 万が一アカウントが不正利用された可能性がある場合は、迅速に運営へお問い合わせ・ご報告ください。
```

今回連絡が遅かったせいで蹴る話も出てたので…

2021-09-18 09:03 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/discord-two-factor.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/blog/discord-two-factor)
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/server/rules/discord)

2021-09-18 09:04 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/discord-two-factor.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/blog/discord-two-factor)
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/server/rules/discord)

2021-09-18 09:06 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/discord-two-factor.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/blog/discord-two-factor)
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/server/rules/discord)

2021-09-21 05:38 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/discord-two-factor.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/blog/discord-two-factor)
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/server/rules/discord)

2021-09-21 05:40 UTC, Omuretsu commented on blog/discord-two-factor.md
> +インターネットは便利な半面様々な情報がやり取りされており、使い方によってはトラブルに巻き込まれる場合があります。特にDiscordにおいては、特定権限からファイルの送信が可能となっています。もしトラブルがあった場合、貴方だけではなく他利用者にも被害が及ぶ場合があります。
修正しました。
確認をおねがいします。

2021-09-21 05:41 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/discord-two-factor.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/blog/discord-two-factor)
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/server/rules/discord)

2021-09-21 05:42 UTC, book000 requested changes

2021-09-21 05:42 UTC, book000 commented on blog/discord-two-factor.md
> +二段階認証を有効にすることで、Discordのアカウントにログインする際は貴方のスマートフォンなどの端末が必須になります。これにより、もしアカウントのパスワードが漏洩した場合でも、不正ログインを防ぐことができます。
```suggestion
二段階認証を有効にすることで、Discordのアカウントにログインする際はあなたのスマートフォンなどの端末が必須になります。これにより、もしアカウントのパスワードが漏洩した場合でも、不正ログインを防ぐことができます。  
```

Ctrl+Fするとファイル内検索できるからオススメ。置き換えもできるよ

2021-09-21 05:44 UTC, book000 approved these changes

2021-09-21 05:45 UTC, merged

2021-09-21 05:46 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/discord-two-factor.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/blog/discord-two-factor)
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/80/server/rules/discord)