文章の修正
jaoafa/jaoweb-docs pull request #84
Opened 2021-09-26 21:01 UTC by Omuretsu

・表題のとおりです。
・校正プラグインの導入により、違和感のある箇所を修正しました。
・一部箇条書きリストの、体裁崩れ修正も含めます。

2021-09-26 21:02 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/guidelines/broadcasts.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/broadcasts)
- [server/guidelines/cities.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/cities)
- [server/guidelines/communications.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/communications)
- [server/guidelines/griefing.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/griefing)
- [server/guidelines/railways.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/railways)

2021-09-26 22:46 UTC, book000 commented
一通り内容は後で見ますが、タイトルは **何をどう変更したのか** をもうすこし分かりやすく書いてください
全部が全部「文章の修正」は流石に無理があります。だったら一つのプルリクに纏めろって話にもなってくる

プルリクをある程度分けるのって

- レビュアーが一つ一つのプルリクに対してレビューをかけすぎないように
- request changesが多くなって見づらくならないために
- もし一つのページの編集丸々ダメってなってプルリクをクローズするときに、巻き込まれたコミットがないようにするために

という理由があります。
緩いリポジトリなので色々強制はしないんですが、せめてタイトルくらいは端的に理解しやすいものにしてください…。通知飛んできて全部「文章の修正」は流石に😱です

2021-09-27 07:48 UTC, Omuretsu commented
大謝罪

2021-09-27 14:41 UTC, book000 requested changes

2021-09-27 14:41 UTC, book000 commented on server/guidelines/cities.md
> +自治体が申請されるたびに、運営は申請の妥当性などを時間をかけて手動で確認し、審議をしているのはこのためです。
これ元の文章もだけど日本語おかしくないですか…？
末尾の「審議をしている理由」につながる文章として「妥当性を確認している」はなんか…？

2021-09-28 00:21 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/guidelines/broadcasts.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/broadcasts)
- [server/guidelines/cities.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/cities)
- [server/guidelines/communications.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/communications)
- [server/guidelines/griefing.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/griefing)
- [server/guidelines/railways.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/railways)

2021-10-01 09:54 UTC, Omuretsu commented on server/guidelines/cities.md
> +自治体が申請されるたびに、運営は申請の妥当性などを時間をかけて手動で確認し、審議をしているのはこのためです。
なおしてみました。

2021-10-01 09:55 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/guidelines/broadcasts.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/broadcasts)
- [server/guidelines/cities.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/cities)
- [server/guidelines/communications.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/communications)
- [server/guidelines/griefing.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/griefing)
- [server/guidelines/railways.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/railways)

2021-10-01 14:17 UTC, book000 requested changes

2021-10-01 14:17 UTC, book000 commented on server/guidelines/cities.md
> +我々運営としては、他のユーザが楽しく遊べるよう、こうしたトラブルを未然に防ぎ、サーバ内の治安の維持に務める必要があります。トラブルを起こしそうなユーザに権限を与えないことも、余計なトラブルを未然に防ぐためです。
```suggestion
我々運営としては、他のユーザが楽しく遊べるよう、こうしたトラブルを未然に防ぎ、サーバ内の治安の維持に努める必要があります。トラブルを起こしそうなユーザに権限を与えないことも、余計なトラブルを未然に防ぐためです。  
```

2021-10-01 15:22 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/guidelines/broadcasts.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/broadcasts)
- [server/guidelines/cities.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/cities)
- [server/guidelines/communications.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/communications)
- [server/guidelines/griefing.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/griefing)
- [server/guidelines/railways.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/railways)

2021-10-01 15:22 UTC, book000 approved these changes

2021-10-01 15:23 UTC, merged

2021-10-01 15:23 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/guidelines/broadcasts.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/broadcasts)
- [server/guidelines/cities.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/cities)
- [server/guidelines/communications.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/communications)
- [server/guidelines/griefing.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/griefing)
- [server/guidelines/railways.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/84/server/guidelines/railways)