文章の修正
jaoafa/jaoweb-docs pull request #85
Opened 2021-09-26 21:07 UTC by Omuretsu

表題のとおりです。

2021-09-26 21:08 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/policies/bans.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/85/server/policies/bans)
- [server/policies/index.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/85/server/policies/)
- [server/policies/permissions.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/85/server/policies/permissions)
- [server/policies/privacy.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/85/server/policies/privacy)

2021-09-27 14:21 UTC, book000 requested changes

2021-09-27 14:21 UTC, book000 commented on server/policies/index.md
> +利用者は運営に対して、さまざまな問い合わせ等を行う場面があるかと思います。その際、短時間に複数回の問い合わせや暴言等が見られた場合は、必要に応じて発言権の取り上げやサービスの利用を制限します。これは必要以上に問い合わせ等が行われた場合、本来不要な運営作業が発生するためです。
ここ、改行していて表示上でリスト表示が切れてますけど意図したものですか？
https://dev.jaoafa.com/jaoweb/jaoafa/pulls/85/server/policies/#免責事項

2021-09-27 22:40 UTC, Omuretsu commented on server/policies/index.md
> +利用者は運営に対して、さまざまな問い合わせ等を行う場面があるかと思います。その際、短時間に複数回の問い合わせや暴言等が見られた場合は、必要に応じて発言権の取り上げやサービスの利用を制限します。これは必要以上に問い合わせ等が行われた場合、本来不要な運営作業が発生するためです。
Fixed🙇‍♂️

2021-09-27 22:41 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/policies/bans.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/85/server/policies/bans)
- [server/policies/index.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/85/server/policies/)
- [server/policies/permissions.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/85/server/policies/permissions)
- [server/policies/privacy.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/85/server/policies/privacy)

2021-09-28 00:22 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/policies/bans.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/85/server/policies/bans)
- [server/policies/index.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/85/server/policies/)
- [server/policies/permissions.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/85/server/policies/permissions)
- [server/policies/privacy.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/85/server/policies/privacy)

2021-09-28 09:11 UTC, book000 approved these changes

2021-09-28 09:11 UTC, merged