文章の修正
jaoafa/jaoweb-docs pull request #87
Opened 2021-09-26 21:19 UTC by Omuretsu

表題のとおりです

2021-09-26 21:20 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [support/faq.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/87/support/faq)
- [support/inquiry.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/87/support/inquiry)

2021-09-26 21:21 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [support/faq.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/87/support/faq)
- [support/inquiry.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/87/support/inquiry)

2021-09-27 14:56 UTC, book000 requested changes

2021-09-27 14:56 UTC, book000 commented on support/inquiry.md
> +なお住所やパスワードなどの、とくにに重要な個人情報は送信しないでください。
```suggestion
なお住所やパスワードなどの、とくに重要な個人情報は送信しないでください。
```

2021-09-27 22:42 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [support/faq.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/87/support/faq)
- [support/inquiry.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/87/support/inquiry)

2021-09-28 00:23 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [support/faq.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/87/support/faq)
- [support/inquiry.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/87/support/inquiry)

2021-09-28 09:07 UTC, book000 approved these changes

2021-09-28 09:07 UTC, merged