feat: モデレーター新規加入についてのスタッフ一覧更新および新規ブログ記事投稿
jaoafa/jaoweb-docs pull request #91
Opened 2021-10-26 11:47 UTC by book000

2021-10-30 20:19 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/202110-new-moderator.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/91/blog/202110-new-moderator)
- [server/profiles.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/91/server/profiles)

2021-10-30 20:20 UTC, Hiratake submitted a review, later dismissed
更新日を今日にして改行を1箇所足しました。
他は特に問題ないと思います。

2021-10-30 20:22 UTC, Hiratake commented
実際のページ見られない人のためにスクリーンショット置いておきます。

![運営者情報](https://user-images.githubusercontent.com/23224932/139557386-29a6c77b-07a4-488f-b00a-ebda5b5e04f2.png)

![モデレーター新規加入のお知らせ](https://user-images.githubusercontent.com/23224932/139557388-339e312b-1160-4fec-b70d-fc17d6763113.png)

2021-10-30 22:35 UTC, lncongruence submitted a review, later dismissed
　　　 ∧　　/ヽ
　　　/／￣￣＼|
　　 ∠＿╋＿＿〉
　　/　①八①　ヽ ＿
　 工ﾆf(_人_)ｴ二|′)ヽ
　　＼ヽヽノノ ノ ヘ |
⊂⌒)_＞―――′イ (＿)
　`ー､_ノ/￣ヽ　｜
　　 ＿|｜　 |　｜
　　(　 人＿ノ　Λ
　　 ＼ス￣￣ﾚ-Λ ＼
　　(￣　)　/ /　＼ﾉ＼
　　 ￣￣　(　ヽ　 ＼_)
　　　　　　＼ノ

2021-10-31 02:27 UTC, Omuretsu requested changes

2021-10-31 02:31 UTC, book000 commented
オムレツのサジェストをマージしました

2021-10-31 02:31 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/202110-new-moderator.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/91/blog/202110-new-moderator)
- [server/profiles.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/91/server/profiles)

2021-10-31 02:31 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/202110-new-moderator.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/91/blog/202110-new-moderator)
- [server/profiles.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/91/server/profiles)

2021-10-31 02:34 UTC, Omuretsu approved these changes

2021-10-31 02:35 UTC, merged