feat: #88 自動切断後、再接続した場合の処理について追加
jaoafa/jaoweb-docs pull request #94
Opened 2021-11-03 11:52 UTC by book000

close #88 

#88 および運営内審議にて承認された事項についてDiscordサーバルールへの反映を行いました。それ以外に一部コード部分にスペースを入れるなどの見栄え調整をしています

以下部分が #88 に該当する部分です。

```
8. 3か月経過によって自動的にMinecraftアカウントとの連携が解除された場合、次の方法で権限を復元することができます。
   1. 連携自動解除後、1週間以内に再連携した場合は自動的に権限が復元されます。
   2. 連携自動解除後、1か月(30日)以内であれば本人から公式Discordサーバの `#support` チャンネルにて申請・運営の判断により手動で権限が復元されます。
9. 運営(Admin・Moderator)についても、連携自動解除後1か月以内に再接続しない場合はAdmin・Moderatorからの脱退を求めます。
```

よろしくお願いします。

2021-11-03 11:52 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/94/server/rules/discord)

2021-11-03 15:23 UTC, Omuretsu requested changes

2021-11-03 15:23 UTC, Omuretsu commented on server/rules/discord.md
> +6. 利用者は、運営が適切と判断できる理由がある場合公式Discordサーバの `#support` チャンネルにて免責事項の4の自動連携解除を期限付きで延期申請することができます。
ここ、長いからもう少し文章を分割した方がよいと思われ
いうてあんま思いつかんけど

2021-11-03 15:23 UTC, Omuretsu commented on server/rules/discord.md
> +   2. 連携自動解除後、1か月(30日)以内であれば本人から公式Discordサーバの `#support` チャンネルにて申請・運営の判断により手動で権限が復元されます。
```suggestion
   2. 連携自動解除後、1か月(30日)以内であれば本人から公式Discordサーバの `#support` チャンネルにて、権限の再付与申請を行うことができます。運営は申請内容について、再付与の可否を判断します。
```

2021-11-04 05:16 UTC, book000 commented on server/rules/discord.md
> +6. 利用者は、運営が適切と判断できる理由がある場合公式Discordサーバの `#support` チャンネルにて免責事項の4の自動連携解除を期限付きで延期申請することができます。
むむ…。まったく私も代替策思いつかないわ
`公式Discordサーバの `#support` チャンネルにて申請` 部分は権限復元申請時も同じだからなんかうまく纏められるならまとめてもいいとは思うんだけどどうすればいいかわからん

2021-11-04 05:17 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/94/server/rules/discord)

2021-11-04 06:14 UTC, Omuretsu commented on server/rules/discord.md
> +6. 利用者は、運営が適切と判断できる理由がある場合公式Discordサーバの `#support` チャンネルにて免責事項の4の自動連携解除を期限付きで延期申請することができます。
```suggestion
6. 特段の事情がありサーバにログインできない場合、利用者は免責事項の4の自動連携解除を期限付きで延期申請することができます。申請理由などをもとに、運営は期限延長の可否を判断します。
```

こんなかんじ？

2021-11-04 06:18 UTC, book000 commented on server/rules/discord.md
> +6. 利用者は、運営が適切と判断できる理由がある場合公式Discordサーバの `#support` チャンネルにて免責事項の4の自動連携解除を期限付きで延期申請することができます。
👌

2021-11-04 06:18 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/94/server/rules/discord)

2021-11-04 06:18 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [server/rules/discord.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/94/server/rules/discord)

2021-11-04 06:43 UTC, Omuretsu approved these changes

2021-11-07 14:15 UTC, Hiratake approved these changes

2021-11-07 14:15 UTC, Hiratake commented
イイン・ジェーン

2021-11-07 14:21 UTC, merged