Windowsアプリ版Minecraft Launcherにプロファイルを移行する方法
jaoafa/jaoweb-docs pull request #95
Opened 2021-11-04 03:01 UTC by kohonayoshi

VScode開くのがめんどくさかったのでパクった

2021-11-04 03:02 UTC, jaotan commented
# 変更のあったファイルプレビュー

2021-11-04 05:18 UTC, book000 commented
中身はまだ見てないですけど、そもそも拡張子ついてないように見えます

2021-11-04 05:31 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-profile-move.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-profile-move)

2021-11-04 06:06 UTC, book000 commented
参考になりそう: https://github.com/jaoafa/jaoweb-docs/blob/main/blog/forge-commentary.md

2021-11-04 06:12 UTC, book000 requested changes

2021-11-04 06:12 UTC, book000 commented on blog/how-to-microsoft-minecraft-launcher-profile-move.md
> +① `.minecraft` フォルダを開く
```suggestion
## 1. `.minecraft` フォルダを開く

`%appdata%\.minecraft` をエクスプローラーのアドレス欄に入力し、アクセスすると Minecraft のフォルダが開けます。

```

2021-11-04 06:12 UTC, book000 commented on blog/how-to-microsoft-minecraft-launcher-profile-move.md
> +② `launcher_profiles.json`(旧ランチャー) と `launcher_profiles_microsoft_store.json`(新ランチャー) を開く
```suggestion
## 2. `launcher_profiles.json`(旧ランチャー) と `launcher_profiles_microsoft_store.json`(新ランチャー) を開く

`.minecraft` フォルダにある `launcher_profiles.json` と、`launcher_profiles_microsoft_store.json` の両方を適当なエディタで開きます。

```

2021-11-04 06:12 UTC, book000 commented on blog/how-to-microsoft-minecraft-launcher-profile-move.md
> +③ 以下のうち👈の絵文字で囲まれた範囲を、旧ランチャーからコピーし新ランチャーの該当する部分に貼り付けて置き換える
```suggestion
## 3. 以下のうち👈の絵文字で囲まれた範囲を、旧ランチャーからコピーし新ランチャーの該当する部分に貼り付けて置き換える

```

2021-11-04 06:12 UTC, book000 commented on blog/how-to-microsoft-minecraft-launcher-profile-move.md
> +④ 新ランチャーを起動してプロファイルがある・正常に起動できることを確認したら終わり
```suggestion
## 4. 新ランチャーを起動してプロファイルがある・正常に起動できることを確認する

新しいMicrosoft Store版のランチャーを起動し、プロファイルが反映されていることとそのプロファイルで起動できることを確認してください。

```

2021-11-04 06:17 UTC, kohonayoshi reviewed
🙏

2021-11-04 09:32 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-profile-move.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-profile-move)

2021-11-04 09:33 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-profile-move.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-profile-move)

2021-11-04 09:33 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-profile-move.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-profile-move)

2021-11-04 09:34 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-profile-move.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-profile-move)

2021-11-04 16:15 UTC, book000 commented
なんかサジェストうまく出さないので画像ですみません
![6B88F3FE-1069-48DE-93F0-9BFFD42B6BA5](https://user-images.githubusercontent.com/8929706/140377185-3d12b509-9fb6-4e20-9792-abc69a7ca513.jpeg)

markdownの形式上、コードブロックの前後に改行が必要です(コードブロックの後が赤くなっちゃってますよね？)。これの修正もお願いします

2021-11-04 16:16 UTC, book000 commented
それが修正されればとりあえず私はapproveかなあ

2021-11-05 10:33 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-profile-move.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-profile-move)

2021-11-05 14:24 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-profile-move.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-profile-move)

2021-11-06 03:19 UTC, Omuretsu requested changes

2021-11-06 03:19 UTC, Omuretsu commented on blog/how-to-microsoft-minecraft-launcher-profile-move.md
> +※一応自分が動作確認して問題はありませんでしたがこれでマイクラぶっ壊れても責任は負いません
```suggestion
※一応自分が動作確認して問題はありませんでしたが、これでマイクラぶっ壊れても責任は負いません
```

細かい句読点とか気になっちゃうんだよなぁ〜というお気持ち

2021-11-06 04:05 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-profile-move.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-profile-move)

2021-11-06 04:05 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-profile-move.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-profile-move)

2021-11-06 16:35 UTC, Hiratake requested changes
英語わからんからアレだけど、ファイル名 `how-to-move-profile-to-new-launcher.md` とかのほうがよくないですか？

2021-11-06 16:35 UTC, Hiratake commented on blog/how-to-microsoft-minecraft-launcher-profile-move.md
> +author: kohonayoshi
`jaoweb` にある `authors.json` の `slug` と同じ文字列を指定しないとエラーになるので、合わせてください。
https://github.com/jaoafa/jaoweb/blob/master/content/blog/authors.json#L70

記事側を `kohona` にするか、 `jaoweb` 側を `kohonayoshi` にするかは好みなので、お好きな方で。

2021-11-06 16:35 UTC, Hiratake commented on blog/how-to-microsoft-minecraft-launcher-profile-move.md
> +Minecraft LauncherがMicrosoftアプリになったせいでプロファイル系が死んだので、被害者が増える前にプロファイルの移行の仕方を伝授します。
以下みたいな感じの文章書くと読みやすいかも。しらんけど。

---

先日、 Minecraft Launcher の [Microsoft Store での配信](https://www.xbox.com/ja-JP/games/store/Minecraft-Launcher/9PGW18NPBZV5) が開始されました。この新しいランチャーでは、「Java Edition」「Bedrock Edition」の両方が利用可能になります。

これまで Minecraft を遊んでこられた方は、今までのランチャーから切り替えを行うことになります。その際に、これまで遊んでいたデータなどを新しいランチャーへ移行したい！という方が多いのではないかと思います。

この記事では、新しい Minecraft Launcher へプロファイルを移行する方法について解説します。

---

2021-11-06 16:35 UTC, Hiratake commented on blog/how-to-microsoft-minecraft-launcher-profile-move.md
> +## 1. `.minecraft` フォルダを開く
`##` の見出し、わりと文字サイズがでかいので、1～4の見出しを `###` に変更して、1の上に `## 移行方法` みたいな見出し増やしたほうがいいかも。（なんか文字の威圧感がすごいので）

![image](https://user-images.githubusercontent.com/23224932/140616851-a0cec7d1-4951-47e0-b303-480cc849fe84.png)

2021-11-06 17:05 UTC, book000 approved these changes

2021-11-06 19:55 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-profile-move.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-profile-move)

2021-11-06 20:13 UTC, kohonayoshi reviewed
ふむ

2021-11-06 20:15 UTC, book000 requested changes

2021-11-06 20:15 UTC, book000 commented on blog/how-to-microsoft-minecraft-launcher-profile-move.md
> +Minecraft LauncherがMicrosoftアプリになったせいでプロファイル系が死んだので、被害者が増える前にプロファイルの移行の仕方を伝授します。
```suggestion
先日、 Minecraft Launcher の [Microsoft Store での配信](https://www.xbox.com/ja-JP/games/store/Minecraft-Launcher/9PGW18NPBZV5) が開始されました。この新しいランチャーでは、「Java Edition」「Bedrock Edition」の両方が利用可能になります。

これまで Minecraft を遊んでこられた方は、今までのランチャーから切り替えを行うことになります。その際に、これまで遊んでいたデータなどを新しいランチャーへ移行したい！という方が多いのではないかと思います。

この記事では、新しい Minecraft Launcher へプロファイルを移行する方法について解説します。
```

2021-11-06 20:17 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-profile-move.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-profile-move)

2021-11-06 20:25 UTC, book000 approved these changes
https://github.com/jaoafa/jaoweb/pull/129 のマージを待ってからマージします。

2021-11-06 20:25 UTC, book000 commented
ファイル名は直す必要があればマージ前に直してください。

2021-11-06 20:58 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-installation-migration.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-installation-migration)

2021-11-06 21:00 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-installations-migration.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-installations-migration)

2021-11-07 01:03 UTC, Hiratake approved these changes

2021-11-07 01:03 UTC, Hiratake commented on blog/how-to-microsoft-minecraft-launcher-installations-migration.md
> +この記事では、新しい Minecraft Launcher へプロファイルを移行する方法について解説します。
文末に半角スペースを2つ設置しないと改行されないので、改行が必要なようなら入れてください。

![image](https://user-images.githubusercontent.com/23224932/140628449-6bd24ee2-a084-4075-b06b-0878dd1454de.png)

2021-11-07 01:03 UTC, Hiratake commented on blog/how-to-microsoft-minecraft-launcher-installations-migration.md
> +createdAt: 2021-11-04
公開前に、公開日と更新日の日付を公開する日のものに変更をおねがいします。

2021-11-07 01:57 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-installations-migration.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-installations-migration)

2021-11-07 02:18 UTC, kohonayoshi reviewed
なるほど

2021-11-07 12:13 UTC, book000 requested changes

2021-11-07 12:13 UTC, book000 commented on blog/how-to-microsoft-minecraft-launcher-installations-migration.md
> +この記事では、新しい Minecraft Launcher へプロファイルを移行する方法について解説します。
```suggestion
この記事では、新しい Minecraft Launcher へプロファイルを移行する方法について解説します。  
```

2021-11-07 12:14 UTC, book000 approved these changes

2021-11-07 12:14 UTC, jaotan commented
# 変更のあったファイルプレビュー
- [blog/how-to-microsoft-minecraft-launcher-installations-migration.md](https://dev.jaoafa.com/jaoweb/jaoafa/pulls/95/blog/how-to-microsoft-minecraft-launcher-installations-migration)

2021-11-07 12:16 UTC, merged